### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Users/.../.cache/vosk'

### ISSUE THREAD

**Issue by pzula** [alphacep/vosk-api#1061]
I finally got vosk CLI command to work in my local environment,  (I had issues here: https://github.com/alphacep/vosk-api/issues/1060) but I'm having a hard time getting it to actually transcribe.  am I supposed to create the directory that is missing in this error or was there something wrong with my installation?  

```
% vosk-transcriber -i /Users/pzula/Downloads/220708_1333.mp3  -o ~/Downloads/test.txt
Traceback (most recent call last):
  File "/Users/pzula/.asdf/installs/python/3.10.0/bin/vosk-transcriber", line 8, in <module>
    sys.exit(main())
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/vosk/transcriber/cli.py", line 62, in main
    transcriber = Transcriber(args)
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/vosk/transcriber/transcriber.py", line 16, in __init__
    self.model = Model(model_path=args.model, model_name=args.model_name, lang=args.lang)
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/vosk/__init__.py", line 50, in __init__
    model_path = self.get_model_path(model_name, lang)
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/vosk/__init__.py", line 63, in get_model_path
    model_path = self.get_model_by_lang(lang)
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/vosk/__init__.py", line 97, in get_model_by_lang
    self.download_model(Path(directory, result_model[0]))
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/vosk/__init__.py", line 102, in download_model
    MODEL_DIRS[3].mkdir()
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/pathlib.py", line 1173, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pzula/.cache/vosk'
Exception ignored in: <function Model.__del__ at 0x105811ab0>
Traceback (most recent call last):
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/vosk/__init__.py", line 56, in __del__
    _c.vosk_model_free(self._handle)
AttributeError: 'Model' object has no attribute '_handle'
 % ls .cache
ls: .cache: No such file or directory
```

**Comment by nshmyrev** [comment]
Run `mkdir -p /Users/pzula/.cache/vosk`

**Comment by nshmyrev** [comment]
Same as #988
