### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

### ISSUE THREAD

**Issue by pzula** [alphacep/vosk-api#1062]
After creating the cache directory as instructed in https://github.com/alphacep/vosk-api/issues/1061, I have yet another error about a missing directory:

```
% vosk-transcriber -i /Users/pzula/Downloads/220708_1333.mp3  -o ~/Downloads/test.txt

vosk-model-small-en-us-0.15.zip: 100%|█████| 39.3M/39.3M [00:30<00:00, 1.34MB/s]
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from /Users/pzula/.cache/vosk/vosk-model-small-en-us-0.15/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:282) Loading HCL and G from /Users/pzula/.cache/vosk/vosk-model-small-en-us-0.15/graph/HCLr.fst /Users/pzula/.cache/vosk/vosk-model-small-en-us-0.15/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:303) Loading winfo /Users/pzula/.cache/vosk/vosk-model-small-en-us-0.15/graph/phones/word_boundary.int
INFO:root:Recognizing /Users/pzula/Downloads/220708_1333.mp3
Traceback (most recent call last):
  File "/Users/pzula/.asdf/installs/python/3.10.0/bin/vosk-transcriber", line 8, in <module>
    sys.exit(main())
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/vosk/transcriber/cli.py", line 68, in main
    transcriber.process_file(args)
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/vosk/transcriber/transcriber.py", line 87, in process_file
    final_result, tot_samples = self.process_entry([args.input, args.output])
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/vosk/transcriber/transcriber.py", line 69, in process_entry
    stream = self.resample_ffmpeg(inputdata[0])
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/site-packages/vosk/transcriber/transcriber.py", line 55, in resample_ffmpeg
    stream = subprocess.Popen(
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/pzula/.asdf/installs/python/3.10.0/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
```

**Comment by nshmyrev** [comment]
You need to install ffmpeg

**Comment by pzula** [comment]
> You need to install ffmpeg

from homebrew?

I wonder if I missed this in the installation instructions somewhere?

**Comment by nshmyrev** [comment]
Yes

**Comment by nortikin** [comment]
debian kills me
apt install ffmpeg:
```bash
Следующие пакеты имеют неудовлетворённые зависимости:
 ffmpeg : Зависит: libavcodec58 (= 7:4.1.9-0+deb10u1)
          Зависит: libavdevice58 (= 7:4.1.9-0+deb10u1) но он не будет установлен
          Зависит: libavfilter7 (= 7:4.1.9-0+deb10u1)
          Зависит: libavformat58 (= 7:4.1.9-0+deb10u1) но он не будет установлен
E: Невозможно исправить ошибки: у вас зафиксированы сломанные пакеты.
```
