### ISSUE TITLE
No such file or directory .cache/vosk

### ISSUE THREAD

**Issue by michael1006** [alphacep/vosk-api#1076]
I've just done a bare-bones installation per the [official tutorial](https://alphacephei.com/vosk/install) on what would seem to be a very standard system, and the `vosk-transcriber` generates an error I have no idea how to fix.

I'm on a Macbook Air M1 running up-to-date Monterey, with Python3 installed via Homebrew. `python3 --version` returns `Python 3.9.13` and `pip3 --version` returns `pip 22.1.1`, both of which are supported according to Vosk docs.

I ran `pip3 install vosk` which seemed to go fine, but when I then try running `vosk-transcribe` on a simple file like `vosk-transcriber -i meditation1.mp4 -o test.txt` I get the following output:

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/vosk-transcriber", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/transcriber/cli.py", line 62, in main
    transcriber = Transcriber(args)
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/transcriber/transcriber.py", line 16, in __init__
    self.model = Model(model_path=args.model, model_name=args.model_name, lang=args.lang)
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/__init__.py", line 50, in __init__
    model_path = self.get_model_path(model_name, lang)
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/__init__.py", line 63, in get_model_path
    model_path = self.get_model_by_lang(lang)
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/__init__.py", line 97, in get_model_by_lang
    self.download_model(Path(directory, result_model[0]))
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/__init__.py", line 102, in download_model
    MODEL_DIRS[3].mkdir()
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mjbaldwin/.cache/vosk'
Exception ignored in: <function Model.__del__ at 0x103a7caf0>
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/__init__.py", line 56, in __del__
    _c.vosk_model_free(self._handle)
AttributeError: 'Model' object has no attribute '_handle'
```

It seems that it's complaining there's no `.cache/vosk` in my user directory. And from the overall output, it seems like it's trying to download a model into that temporary directory but that it perhaps failed to create it first? (I am running the command from my user directory.)

So since I haven't tried to configure anything out of the ordinary, I'm wondering if there's a bug somewhere either in code or installation happening?

Note that `vosk-transcribe --help` works correctly, and both `--list-models` and `--list-languages` gives lots of results.

Thanks!

**Comment by nshmyrev** [comment]
Same as #988

Run pip3 install -U vosk to install 0.3.43, it should work then.
