### ISSUE TITLE
vosk-transcriber fails if path to input file contains a space

### ISSUE THREAD

**Issue by michael1006** [alphacep/vosk-api#1078]
So now that I'm successfully using `vosk-transcriber`, I observed that it was working in some cases and not others. I finally narrowed the bug down to discover that it works perfectly on input paths that do not contain a space, but fails if they contain a space, specifically with a divide-by-zero error. When I run the command:

```
vosk-transcriber -i "/Users/mjbaldwin/free rec/test.wav"  -o "/Users/mjbaldwin/free rec/test.txt"
```

I get:

```
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from /Users/mjbaldwin/.cache/vosk/vosk-model-small-en-us-0.15/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:282) Loading HCL and G from /Users/mjbaldwin/.cache/vosk/vosk-model-small-en-us-0.15/graph/HCLr.fst /Users/mjbaldwin/.cache/vosk/vosk-model-small-en-us-0.15/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:303) Loading winfo /Users/mjbaldwin/.cache/vosk/vosk-model-small-en-us-0.15/graph/phones/word_boundary.int
INFO:root:Recognizing /Users/mjbaldwin/free rec/test.wav
INFO:root:{'text': ''}
INFO:root:File /Users/mjbaldwin/free rec/test.txt processing complete
Traceback (most recent call last):
  File "/opt/homebrew/bin/vosk-transcriber", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/transcriber/cli.py", line 82, in main
    transcriber.process_task_list(args, task_list)    
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/transcriber/transcriber.py", line 170, in process_task_list
    self.process_task_list_pool(task_list)
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/transcriber/transcriber.py", line 166, in process_task_list_pool
    pool.map(self.pool_worker, task_list)
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/opt/homebrew/lib/python3.9/site-packages/vosk/transcriber/transcriber.py", line 156, in pool_worker
    logging.info('Execution time: {:.3f} sec; xRT {:.3f}'.format(elapsed, float(elapsed) * (2 * SAMPLE_RATE) / tot_samples))
ZeroDivisionError: float division by zero
```

While if I remove the space in the title of the the `free rec` directory to become `freerec` and edit my command accordingly:

```
vosk-transcriber -i "/Users/mjbaldwin/freerec/test.wav"  -o "/Users/mjbaldwin/freerec/test.txt"
```

transcription succeeds perfectly. This is on the same input file data, the only difference is the space in the path.

Note that it is only the input file which produces this bug -- spaces in the output file work just fine.

Again this is on a Mac running up-to-date Monterey.

**Comment by michael1006** [comment]
One more detail: by path that includes the filename too -- so even if directories don't contain any spaces, if the filename itself contains one or more spaces it fails as well. And there is no difference between passing in filenames quoted to handle the spaces, or using backslashes to escape the spaces.

**Comment by michael1006** [comment]
I just took a look at it seems the issue might be line 104 of `transcriber.py` that fails to escape spaces or any special characters in the filename when passing it to ffmpeg:

```
cmd = "ffmpeg -nostdin -loglevel quiet -i {} -ar {} -ac 1 -f s16le -".format(str(infile), SAMPLE_RATE)
```

Line 99 presumably contains the same issue as well.

**Comment by nshmyrev** [comment]
@vadimdddd please fix ASAP

**Comment by nshmyrev** [comment]
Merged now
