### ISSUE TITLE
Vosk build fails on Intel MKL 

### ISSUE THREAD

**Issue by shaheenkdr** [alphacep/vosk-api#110]
Trying to build Vosk using Intel MKL instead of Open BLAS , however, the build finishes without any errors : 

```
vosk_ext = Extension('vosk._vosk',
                    define_macros = [('FST_NO_DYNAMIC_LINKING', '1')],
                    include_dirs = [kaldi_root + '/src', kaldi_root + '/tools/openfst/include', 'vosk' , '/opt/intel/mkl/include/'],
                    swig_opts=['-outdir', 'vosk', '-c++'],
                    libraries = kaldi_libraries.extend(['mkl_intel_lp64', 'mkl_core', 'mkl_sequential']),
                    extra_objects = [kaldi_root + '/' + x for x in kaldi_static_libs],
                    sources = ['vosk/' + x for x in sources],
                    extra_link_args = kaldi_link_args.extend(['-L/opt/intel/mkl/lib/intel64', '-Wl,-rpath=/opt/intel/mkl/lib/intel64']),
                    extra_compile_args = ['-std=c++11', '-Wno-sign-compare', '-Wno-unused-variable', '-Wno-unused-local-typedefs'])

```

However, when I try to decode a small model(vosk-model-small-en-us-0.3)  it crashes with the error : 
```
Traceback (most recent call last):
  File "./test_simple.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer, SetLogLevel
  File "/home/shaheen/.local/lib/python3.6/site-packages/vosk/__init__.py", line 1, in <module>
    from .vosk import KaldiRecognizer, Model, SpkModel, SetLogLevel
  File "/home/shaheen/.local/lib/python3.6/site-packages/vosk/vosk.py", line 13, in <module>
    from . import _vosk
ImportError: /home/shaheen/.local/lib/python3.6/site-packages/vosk/_vosk.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cblas_stpmv
```

Please see if this can be fixed

**Comment by nshmyrev** [comment]
I pushed a fix for this in https://github.com/alphacep/vosk-api/commit/31bb0557d9f2a98c8672bbe9013e419d05eee8dc

To build with mkl add KALDI_MKL=1
