### ISSUE TITLE
Multi file transcription doesn't work

### ISSUE THREAD

**Issue by theRAGEhero** [alphacep/vosk-api#1118]
Hello, 
I've tried again the multi file transcription, this time with files that do not have spaces in their names. Still it converts only the first file. 

This is the command I use:
`vosk-transcriber -l it -i ./folder`

This is the log:

```
INFO:root:Execution time: 617.106 sec; xRT 0.117
Traceback (most recent call last):
  File "/home/ale/.local/bin/vosk-transcriber", line 8, in <module>
    sys.exit(main())
  File "/home/ale/.local/lib/python3.8/site-packages/vosk/transcriber/cli.py", line 82, in main
    transcriber.process_task_list(args, task_list)    
  File "/home/ale/.local/lib/python3.8/site-packages/vosk/transcriber/transcriber.py", line 170, in process_task_list
    self.process_task_list_pool(task_list)
  File "/home/ale/.local/lib/python3.8/site-packages/vosk/transcriber/transcriber.py", line 166, in process_task_list_pool
    pool.map(self.pool_worker, task_list)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/ale/.local/lib/python3.8/site-packages/vosk/transcriber/transcriber.py", line 156, in pool_worker
    logging.info('Execution time: {:.3f} sec; xRT {:.3f}'.format(elapsed, float(elapsed) * (2 * SAMPLE_RATE) / tot_samples))
ZeroDivisionError: float division by zero
```
Thank you a lot!

**Comment by vadimdddd** [comment]
Hello, @theRAGEhero, I start to fix this issue, probably smth wrong with file names. Do names contain any special symbols?

**Comment by theRAGEhero** [comment]
Hello @vadimdddd,
The files I was using didn't have any space, the only special symbol was _ (that I used instead of space).
I can send you the original files if you need them.
Thank you

**Comment by vadimdddd** [comment]
@theRAGEhero yup, send it pls, I'll fix this problem. Either for next issue, I will add unzip for .zip models.

**Comment by theRAGEhero** [comment]
Thank you. I've sent the link to Nikolay.

**Comment by nshmyrev** [comment]
Similar to #1715
