### ISSUE TITLE
Exception: Failed to create a model vosk-model-pt-fb-v0.1.1-pruned

### ISSUE THREAD

**Issue by mrrafiopyy** [alphacep/vosk-api#1121]
I was trying to use the vosk-model-pt-fb-v0.1.1-pruned model, but it didn't work for me, and it returns the error:
```
ERROR (VoskAPI:Model():model.cc:122) Folder 'C:\Users\Rafael\Meus arquivos\Programação\vosk-model-pt-fb-v0.1.1-pruned' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.
Traceback (most recent call last):
  File "C:/Users/Rafael/PycharmProjects/Jarvis2/Teste 4.py", line 111, in <module>
    model = Model(r"C:\Users\Rafael\Meus arquivos\Programação\vosk-model-pt-fb-v0.1.1-pruned")
  File "C:\Users\Rafael\PycharmProjects\Jarvis2\venv\lib\site-packages\vosk\__init__.py", line 53, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model
```

**Comment by nshmyrev** [comment]
probably your path specification is wrong, check contents of the folder

**Comment by tomas-viotto** [comment]
Não pode ter espaço nos nomes no caminho
