### ISSUE TITLE
Error looking up function 'vosk_recognizer_set_grm'

### ISSUE THREAD

**Issue by breandan** [alphacep/vosk-api#1235]
I am filing this issue to report the following error after updating from `com.alphacephei:vosk:0.3.38` to `com.alphacephei:vosk:0.3.45` (running JVM 17.0.1 on Mac OS X 13.0.1 aarch64):

```
java.lang.UnsatisfiedLinkError: Error looking up function 'vosk_recognizer_set_grm': dlsym(0x8b31d3b0, vosk_recognizer_set_grm): symbol not found
	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:604)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:580)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:566)
	at com.sun.jna.Native.register(Native.java:1904)
	at com.sun.jna.Native.register(Native.java:1775)
	at org.vosk.LibVosk.<clinit>(LibVosk.java:40)
	at org.vosk.Model.<init>(Model.java:11)
```

cc: @nalbion

**Comment by nalbion** [comment]
This should work on the next release

**Comment by nalbion** [comment]
@nshmyrev could you please do a release to Maven central? 

I've tried to set up a GitHub pipeline based on the Docker & build scripts here, but I'm not sure how to build for Darwin

https://github.com/OpenASR/idear/blob/master/.github/workflows/deploy.yml

**Comment by nshmyrev** [comment]
Hi, I'm working on it. Give me few more days to setup OSX compilation please. Originally this issue tracked at

https://github.com/alphacep/vosk-api/issues/1138

**Comment by vikasthange** [comment]
used java maven dependency version 0.3.45 and still having same error.

**Comment by timmolter** [comment]
Yes, 0.3.45 is broken on Mac Intel and M1 still:
```
java.lang.UnsatisfiedLinkError: Error looking up function 'vosk_recognizer_set_grm': dlsym(0x8c453340, vosk_recognizer_set_grm): symbol not found
        at com.sun.jna.Function.<init>(Function.java:252)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:576)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:562)
```

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/1422
