### ISSUE TITLE
32 bit version in Java

### ISSUE THREAD

**Issue by argen666** [alphacep/vosk-api#1315]
Hi, I'm trying to use the java library in 32-bit system, but I'm getting an error:

18:52:32,912 ERROR java.lang.reflect.InvocationTargetException
java.lang.UnsatisfiedLinkError: %1 is not a valid Win32 application.
	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Native.register(Native.java:1723)
	at org.vosk.LibVosk.<clinit>(LibVosk.java:38)
	at org.vosk.Model.<init>(Model.java:11)

I have downloaded a 32-bit DLLs here:
https://github.com/alphacep/vosk-api/releases/download/v0.3.38/vosk-win32-0.3.38.zip

**Comment by nshmyrev** [comment]
You have "%1" somewhere, it shouldn't be there actually, there must be library name. Not sure where it come from, you'd better check the source

**Comment by argen666** [comment]
Thanks
