### ISSUE TITLE
libvosk.so :undefined symbol:_ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

### ISSUE THREAD

**Issue by 66gobc** [alphacep/vosk-api#1437]
Traceback (most recent call last):
  File "wake_up_vosk_recognizer.py", line 2, in <module>
    import vosk
  File "/home/rpdzkj/archiconda3/envs/py38/lib/python3.8/site-packages/vosk/__init__.py", line 36, in <module>
    _c = open_dll()
  File "/home/rpdzkj/archiconda3/envs/py38/lib/python3.8/site-packages/vosk/__init__.py", line 30, in open_dll
    return _ffi.dlopen(os.path.join(dlldir, "libvosk.so"))
OSError: cannot load library '/home/rpdzkj/archiconda3/envs/py38/lib/python3.8/site-packages/vosk/libvosk.so': /home/rpdzkj/archiconda3/envs/py38/lib/python3.8/site-packages/vosk/libvosk.so: undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev

**Comment by nshmyrev** [comment]
Same as #1253, you need newer libstdc++
