### ISSUE TITLE
Android Crash on release mode

### ISSUE THREAD

**Issue by sGeeK44** [alphacep/vosk-api#1458]
When android app is build with `def enableProguardInReleaseBuilds = true`, application crash on LibVosk initialiation with that error:

```
11-04 15:22:30.599 10918 11365 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Can't obtain peer field ID for class com.sun.jna.Pointer
11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at com.sun.jna.Native.initIDs(Native Method)
11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at com.sun.jna.Native.<clinit>(Unknown Source:333)
11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at org.vosk.LibVosk.<clinit>(Unknown Source:4)
11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at org.vosk.Model.<init>(Unknown Source:0)
11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at z7.k.i(Unknown Source:6)
11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at z7.k.b(Unknown Source:0)
11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at z7.h.run(Unknown Source:12)
11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

To **fix** it need to add rule `-keep class com.sun.jna.** { *; }` in `proguard-rules.pro` file.

**Comment by sGeeK44** [comment]
Maybe when can add this tips in android/Readme.md ?
I speet severals hours to find reason and associated fix. I can be helpful for other users.

**Comment by nshmyrev** [comment]
Sure, please submit a patch

**Comment by mmhmofu** [comment]
> When android app is build with `def enableProguardInReleaseBuilds = true`, application crash on LibVosk initialiation with that error:
> 
> ```
> 11-04 15:22:30.599 10918 11365 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Can't obtain peer field ID for class com.sun.jna.Pointer
> 11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at com.sun.jna.Native.initIDs(Native Method)
> 11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at com.sun.jna.Native.<clinit>(Unknown Source:333)
> 11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at org.vosk.LibVosk.<clinit>(Unknown Source:4)
> 11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at org.vosk.Model.<init>(Unknown Source:0)
> 11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at z7.k.i(Unknown Source:6)
> 11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at z7.k.b(Unknown Source:0)
> 11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at z7.h.run(Unknown Source:12)
> 11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
> 11-04 15:22:30.599 10918 11365 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
> ```
> 
> To **fix** it need to add rule `-keep class com.sun.jna.** { *; }` in `proguard-rules.pro` file.

hi i have the same problem too.But after add rule,the exception turns to 
java.lang.ExceptionInInitializerError
at org.vosk.LibVosk.vosk_model_new(Native Method)
at e.b.a.()
at e.b.c.k.a()
at e.b.c.f.run(lambda)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.IllegalArgumentException: Can't create an instance of class e.b.a, requires a public no-arg constructor: java.lang.NoSuchMethodException: []
at com.sun.jna.Klass.newInstance()
at com.sun.jna.NativeMappedConverter.defaultValue()
at com.sun.jna.NativeMappedConverter.()
at com.sun.jna.NativeMappedConverter.getInstance()
at com.sun.jna.Structure$FFIType.get()
at com.sun.jna.Structure$FFIType.get()
at com.sun.jna.Native.register()
at com.sun.jna.Native.register()
at org.vosk.LibVosk.()
... 7 more
Caused by: java.lang.NoSuchMethodException: []
at java.lang.Class.getConstructor0(Class.java:2204)
at java.lang.Class.getDeclaredConstructor(Class.java:2050)
... 16 more
have you met this problem? please help

**Comment by drindt** [comment]
```text
-dontwarn java.awt.*
-keep class * extends com.sun.jna.** { *; }
-keep class com.sun.jna.** { *; }
```
