### ISSUE TITLE
Model en-gb-0.1 in model-list.json does not work

### ISSUE THREAD

**Issue by papoteur-mga** [alphacep/vosk-api#1470]
I tried to use the model referenced in model-list.json called en-gb-0.1 with nerd-dictation.
But this model is not recognized as such when trying to open it.
```
ERROR (VoskAPI:Model():model.cc:122) Folder '/home/yves/.config/vosk-models/vosk-model-en-gb-0.1' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.
Traceback (most recent call last):
  File "/usr/bin/nerd-dictation", line 1974, in <module>
    main()
  File "/usr/bin/nerd-dictation", line 1970, in main
    args.func(args)
  File "/usr/bin/nerd-dictation", line 1835, in <lambda>
    func=lambda args: main_begin(
  File "/usr/bin/nerd-dictation", line 1437, in main_begin
    found_any = text_from_vosk_pipe(
  File "/usr/bin/nerd-dictation", line 970, in text_from_vosk_pipe
    model = vosk.Model(vosk_model_dir)
  File "/usr/lib/python3.10/site-packages/vosk/__init__.py", line 53, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model
```

**Comment by papoteur-mga** [comment]
I add information on the context:
Mageia 9
python3-vosk-api-0.3.43
lib64kaldi-vosk-git20220817

**Comment by nshmyrev** [comment]
Fixed now, thank you for the report. Overall it is a very old model, not really recommended.
