### ISSUE TITLE
where to get the dictionary of vosk-model-en-us-0.22-lgraph

### ISSUE THREAD

**Issue by YangangCao** [alphacep/vosk-api#1555]
Hi, dear author, I want to get the dictionary of vosk-model-en-us-0.22-lgraph to check every phone in a word, where can I get? Thanks very much

**Comment by nshmyrev** [comment]
It is inside the compilation package

https://alphacephei.com/vosk/models/vosk-model-en-us-0.22-compile.zip

**Comment by YangangCao** [comment]
ok got it, thanks for your quick and accurate reply!

**Comment by YangangCao** [comment]
Hi, sorry to bother you, I find some phone which is hard to read, for example
electromagnetic electromagnetic @_B l_I E_I k_I t_I r_I oU_I m_I {_I g_I n_I E_I 4_I I_I k_E
electromagnetic electromagnetic @_B l_I E_I k_I t_I r_I oU_I m_I {_I g_I n_I E_I t_I I_I k_E
electromagnetic electromagnetic I_B l_I E_I k_I 4_I r_I oU_I m_I {_I g_I n_I E_I 4_I I_I k_E
electromagnetic electromagnetic I_B l_I E_I k_I t_I r_I oU_I m_I {_I g_I n_I E_I t_I I_I k_E

what's 4_I ?
And the word "electromagnetic" have 4 kinds of phone arrangements, I want to calculate GOP(goodness of pronunciation), how to decide the only one phone arrangement?

**Comment by nshmyrev** [comment]
> what's 4_I ?

4 is a sampa phone something like "ch".

_I is for word internal, you are probably looking inside intermediate lexicon instead of original one.

> I want to calculate GOP(goodness of pronunciation), how to decide the only one phone arrangement?

run alignment

**Comment by YangangCao** [comment]
thanks for your reply, it help me a lot

**Comment by YangangCao** [comment]
Hi dear author, why the vosk use different phone system with Kaldi? 
for example, "@", "{", "4"  in vosk model, but doesn't in Kaldi model, 
Any idea to map from one to the other?

**Comment by nshmyrev** [comment]
That particular model uses different phoneset unfortunately. You can still map it easily, it is a simple mapping. Other models like gigaspeech use standard cmu dictionary

**Comment by YangangCao** [comment]
Thanks for you quick and accurate reply, I know gigaspeech model right know and it is good enough to me, I don't plan to map phoneset! thanks!

**Comment by wenxiwu777** [comment]
HI, I unzip vosk-model-en-us-0.22.zip inside a folder called "model", and my code file is in the same level of the folder "model", 

the hierarchy is illustrated as the follow:

code.py (at level0)
model (at level0)
    --  vosk-model-en-us-0.22 (at level1)
           ---- am (at level2)
           ---- conf (at level2)
           ---- graph (at level2)
           ---- ivector (at level2)
           ... ...


and my code fragment is as the follow:
import speech_recognition as sr
from pydub import AudioSegment
from vosk import KaldiRecognizer, Model
import wave

wavFilePath = '/Users/wuwenxi/Downloads/fffff.wav'
wf = wave.open(wavFilePath, 'rb')

def recognizeAudio(wavFilePath):
    recognizer = sr.Recognizer()
    model = Model(model_name="vosk-model-en-us-0.22")
    rec = KaldiRecognizer(model, wf.getframerate())
    rec.SetWords(True)
    
    while True:
        data = wf.readframes(100)
        if (len(data) == 0):
            break
        if rec.AcceptWaveform(data):
            print(rec.Result())
        else:
            print(rec.PartialResult())
            
    print(rec.FinalResult())
        

#####
if __name__ == '__main__':
    recognizeAudio(wavFilePath)


NOW the issue occurred, it outputs the following error:
vosk-model-en-us-0.22.zip: 0.00B [00:00, ?B/s]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:
... ...

it displays "vosk-model-en-us-0.22.zip: 0.00B [00:00, ?B/s]"
the weird thing is that the "vosk-model-en-us-0.22.zip" is not in the model folder at all, after the unzip done I already removed it from the model folder. 
So i have no idea of what is wrong here, please help me to figure it out, THANKS.

**Comment by nshmyrev** [comment]
> HI, I unzip vosk-model-en-us-0.22.zip inside a folder called "model", and my code file is in the same level of the folder "model",
> 
> the hierarchy is illustrated as the follow:
> 
> def recognizeAudio(wavFilePath): recognizer = sr.Recognizer() model = Model(model_name="vosk-model-en-us-0.22") rec = KaldiRecognizer(model, wf.getframerate()) rec.SetWords(True)
> 

Use `model_path` argument instead of `model_name`.

**Comment by wenxiwu777** [comment]
> > HI, I unzip vosk-model-en-us-0.22.zip inside a folder called "model", and my code file is in the same level of the folder "model",
> > the hierarchy is illustrated as the follow:
> > def recognizeAudio(wavFilePath): recognizer = sr.Recognizer() model = Model(model_name="vosk-model-en-us-0.22") rec = KaldiRecognizer(model, wf.getframerate()) rec.SetWords(True)
> 
> Use `model_path` argument instead of `model_name`.

Now the error is gone, it seems working for me, thanks a lot!
