### ISSUE TITLE
The error of the exe application in python

### ISSUE THREAD

**Issue by max32323** [alphacep/vosk-api#1581]
When I try to make a python application using the vosk library, this is highlighted:
Traceback (most recent call last): 
File "exemple.py", line 2, in <module> 
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load 
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked 
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked 
File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module 
File "voicehelper.py", line 3, in <module> 
import vosk 
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load 
File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked 
File "<frozen importlib._bootstrap>", line 688, in _load_unlocked 
File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module 
File "vosk\__init__.py", line 36, in <module> 
File "vosk\__init__.py", line 27, in open_dll 
File "os.py", line 1118, in add_dll_directory 
FileNotFoundError: [WinError 2] Не удается найти указанный файл: 'C:\\Users\\User\\AppData\\Local\\Temp\\_MEI81202\\vosk'

As I understand it, the problem is in a file that I do not have, but I did not touch or delete anything. I have downloaded the library. How can I fix this bug?(I have no errors when running in pytharm)

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/602
