### ISSUE TITLE
vosk-model-de-tuda-0.6-900k ((VoskAPI:ReadInternal():const-arpa-lm.cc:610) ConstArpaLm section reading failed)

### ISSUE THREAD

**Issue by newmutableyouptryou** [alphacep/vosk-api#1606]
Hi! Please tell me, when I load the model, I get the following error. I have 16GB of RAM, or does this model require 16GB of free RAM space? When I get this error, my RAM is 60% full. Or is it related to another problem? Other models with a smaller size load and work correctly. Thanks

LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from C:/Models/vosk-model-de-tuda-0.6-900k/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from C:/Models/vosk-model-de-tuda-0.6-900k/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:297) Loading words from C:/Models/vosk-model-de-tuda-0.6-900k/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:308) Loading winfo C:/Models/vosk-model-de-tuda-0.6-900k/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:315) Loading subtract G.fst model from C:/Models/vosk-model-de-tuda-0.6-900k/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:317) Loading CARPA model from C:/Models/vosk-model-de-tuda-0.6-900k/rescore/G.carpa
ERROR (VoskAPI:ReadInternal():const-arpa-lm.cc:610) ConstArpaLm section reading failed.
Traceback (most recent call last):
File "C:\Speech\Server.py", line 62, in
vosk_model = Model(model_path)
^^^^^^^^^^^^^^^^^
File "C:\Python\Lib\site-packages\vosk_init_.py", line 57, in init
raise Exception("Failed to create a model")
Exception: Failed to create a model

**Comment by nshmyrev** [comment]
Probably G.carpa you downloaded is corrupt. You can download and unpack again.

**Comment by CactusJack1393** [comment]
I did, but... a Vosk version is 0.3.45

LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from C:/Models/vosk-model-de-tuda-0.6-900k/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from C:/Models/vosk-model-de-tuda-0.6-900k/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:297) Loading words from C:/Models/vosk-model-de-tuda-0.6-900k/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:308) Loading winfo C:/Models/vosk-model-de-tuda-0.6-900k/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:315) Loading subtract G.fst model from C:/Models/vosk-model-de-tuda-0.6-900k/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:317) Loading CARPA model from C:/Models/vosk-model-de-tuda-0.6-900k/rescore/G.carpa
ERROR (VoskAPI:ReadInternal():const-arpa-lm.cc:610) ConstArpaLm <LmStates> section reading failed.
Traceback (most recent call last):
  File "C:\Speech\Server.py", line 62, in <module>
    vosk_model = Model(model_path)
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\vosk\__init__.py", line 57, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model

**Comment by newmutableyouptryou** [comment]
Name: vosk  Version: 0.3.45
I did, but it doesn't work.
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from C:/Models/vosk-model-de-tuda-0.6-900k/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from C:/Models/vosk-model-de-tuda-0.6-900k/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:297) Loading words from C:/Models/vosk-model-de-tuda-0.6-900k/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:308) Loading winfo C:/Models/vosk-model-de-tuda-0.6-900k/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:315) Loading subtract G.fst model from C:/Models/vosk-model-de-tuda-0.6-900k/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:317) Loading CARPA model from C:/Models/vosk-model-de-tuda-0.6-900k/rescore/G.carpa
ERROR (VoskAPI:ReadInternal():const-arpa-lm.cc:610) ConstArpaLm <LmStates> section reading failed.
Traceback (most recent call last):
  File "C:\Speech\Server.py", line 62, in <module>
    vosk_model = Model(model_path)
                 ^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\vosk\__init__.py", line 57, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model

**Comment by nshmyrev** [comment]
Well, probably you don't have enough memory. Use our german model https://alphacephei.com/vosk/models/vosk-model-de-0.21.zip, it is better anyway.

**Comment by nshmyrev** [comment]
Or this one https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_de_fastconformer_hybrid_large_pc, it is also much better

**Comment by newmutableyouptryou** [comment]
Thanks a lot for the help!

**Comment by MonoMarkor** [comment]
> Or this one https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_de_fastconformer_hybrid_large_pc, it is also much better

how can we use this model? i am trying:
        stt_model = Model('./stt_de_fastconformer_hybrid_large_pc.nemo')
        speaker_model = SpkModel('./vosk-model-spk-0.4')
        self.rec=KaldiRecognizer(stt_model,16000,speaker_model)

but i get error     raise Exception("Failed to create a model")
Exception: Failed to create a model

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/991
