### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by sajkamal** [alphacep/vosk-api#1609]
Hello, 

I am trying to run VOSK and running into this error. Any help appreciated?

  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
Exception ignored in: <function Model.__del__ at 0x105138900>
Traceback (most recent call last):
  File "/Users/sajjadk/dev/voice_vosk/voice_vosk/lib/python3.11/site-packages/vosk/__init__.py", line 60, in __del__
    _c.vosk_model_free(self._handle)
                       ^^^^^^^^^^^^
AttributeError: 'Model' object has no attribute '_handle'

**Comment by nshmyrev** [comment]
It should be fixed, please try again

**Comment by nshmyrev** [comment]
Same as #1137
