### ISSUE TITLE
error creating model 

### ISSUE THREAD

**Issue by cookmonster** [alphacep/vosk-api#1639]
i have been trying to get my bot to take vosk i think it will work to the best but i am having this error:

ERROR (VoskAPI:Model():model.cc:122) Folder 'model' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.
Traceback (most recent call last):
  File "/home/timmy/Desktop/ava/ava18.py", line 22, in <module>
    wake_up = newwakeup()
  File "/home/timmy/Desktop/ava/mpt/mptpkg/newwakeup.py", line 36, in newwakeup
    voice_input = speech.recognize_vosk(audio)
  File "/home/timmy/.local/lib/python3.10/site-packages/speech_recognition/__init__.py", line 1442, in recognize_vosk
    self.vosk_model = Model("model")
  File "/home/timmy/.local/lib/python3.10/site-packages/vosk/__init__.py", line 57, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model

if you need anything let me know

**Comment by cookmonster** [comment]
i even went from vosk import model
that didnt work

**Comment by cookmonster** [comment]
dont forget to check around so if anyone uses pip speech recognition dont think its easy as one line of code it is vosk.Model('file_spot')
