### ISSUE TITLE
Failed to create model on Linux

### ISSUE THREAD

**Issue by igoruskortsev** [alphacep/vosk-api#1676]
Vosk library 0.3.45 working well on windows(embedded spring tomcat, wildfly 29) ubuntu, but not working on Debian x86_64 Wildfly 29.

pom.xml dependencies:
```
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.alphacephei</groupId>
            <artifactId>vosk</artifactId>
            <version>0.3.45</version>
        </dependency>
```
Sample of code:
```
    public String toText(byte[] body) {
        try {
            var path = "/opt/wildfly/29/tmpf/";
            var modelPath = "/opt/wildfly/29/tmpf/vosk_voice_model_small";

            //write to file
            FileUtils.writeByteArrayToFile(new File(path + "tempvoice.ogg"), body);

            //convert to wav
            File source = new File(path + "tempvoice.ogg");
            File target = new File(path + "tempvoice.wav");

            AudioAttributes audio = new AudioAttributes();
            audio.setCodec("pcm_s16le");
            audio.setBitRate(128000);
            audio.setChannels(1);
            audio.setSamplingRate(16000);

            EncodingAttributes attrs = new EncodingAttributes();
            attrs.setOutputFormat("wav");
            attrs.setAudioAttributes(audio);

            Encoder encoder = new Encoder();
            encoder.encode(new MultimediaObject(source), target, attrs);
            System.out.println("Completed convert to file: " + target.getAbsolutePath());


            //whats there
            LibVosk.setLogLevel(LogLevel.INFO);
            log.info("Model path - {}", modelPath);
            Model model = new Model(modelPath);
            InputStream ais = AudioSystem.getAudioInputStream(new BufferedInputStream(new FileInputStream(path + "tempvoice.wav")));
            Recognizer recognizer = new Recognizer(model, 16000);
            int nbytes;
            byte[] b = new byte[4096];
            while ((nbytes = ais.read(b)) >= 0) {
                if (recognizer.acceptWaveForm(b, nbytes)) {
                    System.out.println(recognizer.getResult());
                } else {
                    System.out.println(recognizer.getPartialResult());
                }
            }

            var result = recognizer.getFinalResult();
            JSONObject json = new JSONObject(result);
            var text = json.get("text");
            return text.toString();
        } catch (Exception e) {
            log.error(e.getMessage(), e);
            throw new RuntimeException(e);
        }
    }
```

stackTrace:
```
2024-12-06 22:13:40,659 INFO  [stdout] (pool-19-thread-3) Completed convert to file: /opt/wildfly/29/tmpf/tempvoice.wav
2024-12-06 22:13:41,008 INFO  [stdout] (pool-19-thread-3) 2024-12-06T22:13:41.008+03:00  INFO 188876 --- [ool-19-thread-3] c.a.app.speech.SpeechRecognizer      : Model path - /opt/wildfly/29/tmpf/vosk_voice_model_small
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 2024-12-06T22:13:41.009+03:00 ERROR 188876 --- [ool-19-thread-3] c.a.app.speech.SpeechRecognizer      : Failed to create a model
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) java.io.IOException: Failed to create a model
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 	at deployment.myapp-1.3.3.war//org.vosk.Model.<init>(Model.java:14) ~[vosk-0.3.45.jar:na]
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 	at deployment.myapp-1.3.3.war//com.test.app.speech.SpeechRecognizer.toText(SpeechRecognizer.java:85) ~[classes:na]
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 	at deployment.myapp-1.3.3.war//com.test.app.service.MessageHandlerService.handleMessage(MessageHandlerService.java:277) ~[classes:na]
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 	at deployment.myapp-1.3.3.war//com.test.app.service.MessageHandlerService.lambda$checkMessages$4(MessageHandlerService.java:110) ~[classes:na]
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[na:na]
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[na:na]
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3) 	at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]
2024-12-06 22:13:41,010 INFO  [stdout] (pool-19-thread-3)
```

**Comment by nshmyrev** [comment]
The message says model path is wrong, you need to check the actual path of the model files in file manager / terminal

**Comment by igoruskortsev** [comment]
> The message says model path is wrong, you need to check the actual path of the model files in file manager / terminal

I am sure model path is correct, it is same for model and temp audio files and store in DB. And of course i check it via terminal.
I checked model files several times, re download big and small models - no result. I can't understand what i do wrong
![Screenshot 2024-12-08 124900](https://github.com/user-attachments/assets/cbed56d9-ded7-469b-bd03-5c05f5611e5e)

**Comment by nshmyrev** [comment]
ls output here shows you do not have necessary files in the model (there must be am and conf folders at least).

**Comment by igoruskortsev** [comment]
> ls output here shows you do not have necessary files in the model (there must be am and conf folders at least).

No, my bad, i just cut a screenshot. Here is a full list of files in vosk_voice_model_small folder
![image](https://github.com/user-attachments/assets/512864b0-fb11-4e09-91e4-172773d8a1cc)

**Comment by kartman1991** [comment]
> > ls output here shows you do not have necessary files in the model (there must be am and conf folders at least).

 No, my bad, i just cut a screenshot. Here is a full list of files in vosk_voice_model_small folder
 ![image](https://private-user-images.githubusercontent.com/71931493/393624164-512864b0-fb11-4e09-91e4-172773d8a1cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MjcyNjEsIm5iZiI6MTczMzcyNjk2MSwicGF0aCI6Ii83MTkzMTQ5My8zOTM2MjQxNjQtNTEyODY0YjAtZmIxMS00ZTA5LTkxZTQtMTcyNzczZDhhMWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA2NDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNDMzYmZhOGY2NTBjYzgzM2JhMjFkMGQ4Y2JjMzIwOTNjNmE5MWU5ODY2NzY5ZWU2MGI4MDYzNTU1MTY1NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SuJHWMZihe6Te2NOvCzP-x0gLr7EV329qgr88XzkLmU)

**Comment by igoruskortsev** [comment]
The problem was resolved. I just need allow Wildfly user necessary rights for reading that folder. I copied via ssh (scp -r model_folder ...) and has access my user only
