### ISSUE TITLE
Crash program when run inference

### ISSUE THREAD

**Issue by AlexTraan** [alphacep/vosk-api#224]
Hi community,

My program sometimes face "ASSERTION_FAILED (VoskAPI:Init():kaldi-vector.cc:168) Assertion failed: (dim >= 0)" crashing, the full trace as below:
"(gdb) bt full
#0  __libc_do_syscall () at ../ports/sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:44
No locals.
#1  0x76c45ee6 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        _a1 = 0
        _a3tmp = 6
        _a1tmp = 0
        _a3 = 6
        _nametmp = 268
        _a2tmp = 895
        _a2 = 895
        _name = 268
        _sys_result = <optimized out>
        pd = 0x76ff5000
        pid = 0
        selftid = 895
#2  0x76c46bee in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {
            __val = {6, 6452604, 19, 0, 0, 2130704712, 1, 1996454384, 1996443648, 0, 6447692,
              0, 1, 1996484608, 2130705020, 1996364693, 1996454384, 1, 1, 0, 6048769,
              1992448936, 2130704692, 2130704708, 2130704692, 6049232, 0, 0, 0, 1996383088,
              0, 0}}, sa_flags = 1996444864, sa_restorer = 0x76ff5000}
        sigs = {__val = {32, 0 <repeats 31 times>}}
#3  0x004b7ce0 in kaldi::KaldiAssertFailure_ (func=<optimized out>, file=<optimized out>,
    line=line@entry=168, cond_str=0x0) at kaldi-error.cc:238
No locals.
#4  0x0044e164 in kaldi::Vector<float>::Init (dim=-78240, this=0x7efffa28)
    at kaldi-vector.cc:168
---Type <return> to continue, or q <return> to quit---
        size = <optimized out>
        data = <optimized out>
        free_data = 0x1e9
#5  kaldi::Vector<float>::Resize (this=this@entry=0x7efffa28, dim=dim@entry=-78240,
    resize_type=resize_type@entry=kaldi::kUndefined) at kaldi-vector.cc:221
No locals.
#6  0x000430c8 in KaldiRecognizer::AcceptWaveform (this=0x639c38,
    data=0x76be2008 "\363\377\346\377\346\377\361\377\357\377\352\377\361\377\357\377\367\377\365\377\354\377\360\377\365\377\372\377\375\377\372\377\376\377\376\377\372\377\367\377\376\377\004", len=<optimized out>) at ../src/kaldi_recognizer.cc:220
        wave = {<kaldi::VectorBase<float>> = {data_ = 0x0, dim_ = 0}, <No data fields>}
#7  0x00042334 in vosk_recognizer_accept_waveform (recognizer=<optimized out>,
    data=<optimized out>, length=<optimized out>) at ../src/vosk_api.cc:61
No locals.
#8  0x0003e4fc in main (argc=1, argv=0x7efffbd4) at main.c:731
        ret = 11
        avail_data = 4294966807
        ptrIsWrapAround = 0x7efffa58
        mean_probability = 0
        final = 0
        isWrapAround = 0

"

the assertion information show up quite clear, however i have no idea to fix it.
 can anyone give me some suggestion?

**Comment by nshmyrev** [comment]
You submit wave file of zero length into the recognizer. Not a great idea. Check the length before acceptwaveform and ignore this chunk.

Also pull request to check the length of the wav vector in the beginning of the AcceptWaveform would be nice.

**Comment by AlexTraan** [comment]
@nshmyrev 
"Also pull request to check the length of the wav vector in the beginning of the AcceptWaveform would be nice"
Sorry i not fully understand this statement. Can you help to more explain?

**Comment by nshmyrev** [comment]
> Sorry i not fully understand this statement. Can you help to more explain?

It would help if you fork the repo, add a check for zero length input in the code and submit a pull request so I can merge it.

Thank you!
