### ISSUE TITLE
Error using examples

### ISSUE THREAD

**Issue by xMpOnEx** [alphacep/vosk-api#332]
I've all installed like that: [Installation](https://alphacephei.com/vosk/install)
How you see I use Python (3.7) on Raspberry 3
I got an issue using [test_microphone.py](https://github.com/alphacep/vosk-api/blob/master/python/example/test_microphone.py):

`Traceback (most recent call last):
  File "/home/pi/test_microphone.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer
  File "/home/pi/test_microphone.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer
ImportError: cannot import name 'Model' from 'vosk' (/home/pi/test_microphone.py)`

anyone can help me?

**Comment by nshmyrev** [comment]
Run

`python3 -v /home/pi/test_microphone.py`

and provide the full output

**Comment by xMpOnEx** [comment]
```
`import` _frozen_importlib#frozen
import _imp#builtin
import '_thread'#<class '_frozen_importlib.BuiltinImporter'>
import '_warnings'#<class '_frozen_importlib.BuiltinImporter'>
import '_weakref'#<class '_frozen_importlib.BuiltinImporter'>
#installing zipimport hook
import 'zipimport'#<class '_frozen_importlib.BuiltinImporter'>
#installed zipimport hook
import '_frozen_importlib_external'#<class '_frozen_importlib.FrozenImporter'>
import '_io'#<class '_frozen_importlib.BuiltinImporter'>
import 'marshal'#<class '_frozen_importlib.BuiltinImporter'>
import 'posix'#<class '_frozen_importlib.BuiltinImporter'>
import _thread#previously loaded ('_thread')
import '_thread'#<class '_frozen_importlib.BuiltinImporter'>
import _weakref#previously loaded ('_weakref')
import '_weakref'#<class '_frozen_importlib.BuiltinImporter'>
#/usr/lib/python3.7/encodings/__pycache__/__init__.cpython-37.pyc matches /usr/lib/python3.7/encodings/__init__.py
#code object from '/usr/lib/python3.7/encodings/__pycache__/__init__.cpython-37.pyc'
#/usr/lib/python3.7/__pycache__/codecs.cpython-37.pyc matches /usr/lib/python3.7/codecs.py
#code object from '/usr/lib/python3.7/__pycache__/codecs.cpython-37.pyc'
import '_codecs'#<class '_frozen_importlib.BuiltinImporter'>
import 'codecs'#<_frozen_importlib_external.SourceFileLoader object at 0x7675e670>
#/usr/lib/python3.7/encodings/__pycache__/aliases.cpython-37.pyc matches /usr/lib/python3.7/encodings/aliases.py
#code object from '/usr/lib/python3.7/encodings/__pycache__/aliases.cpython-37.pyc'
import 'encodings.aliases'#<_frozen_importlib_external.SourceFileLoader object at 0x767701d0>
import 'encodings'#<_frozen_importlib_external.SourceFileLoader object at 0x7675e350>
#/usr/lib/python3.7/encodings/__pycache__/utf_8.cpython-37.pyc matches /usr/lib/python3.7/encodings/utf_8.py
#code object from '/usr/lib/python3.7/encodings/__pycache__/utf_8.cpython-37.pyc'
import 'encodings.utf_8'#<_frozen_importlib_external.SourceFileLoader object at 0x76774b50>
import '_signal'#<class '_frozen_importlib.BuiltinImporter'>
 /usr/lib/python3.7/encodings/__pycache__/latin_1.cpython-37.pyc matches /usr/lib/python3.7/encodings/latin_1.py
#code object from '/usr/lib/python3.7/encodings/__pycache__/latin_1.cpython-37.pyc'
import 'encodings.latin_1'#<_frozen_importlib_external.SourceFileLoader object at 0x76778170>
#/usr/lib/python3.7/__pycache__/io.cpython-37.pyc matches /usr/lib/python3.7/io.py
#code object from '/usr/lib/python3.7/__pycache__/io.cpython-37.pyc'
#/usr/lib/python3.7/__pycache__/abc.cpython-37.pyc matches /usr/lib/python3.7/abc.py
#code object from '/usr/lib/python3.7/__pycache__/abc.cpython-37.pyc'
import '_abc'#<class '_frozen_importlib.BuiltinImporter'>
import 'abc'#<_frozen_importlib_external.SourceFileLoader object at 0x767783f0>
import 'io'#<_frozen_importlib_external.SourceFileLoader object at 0x76778250>
#/usr/lib/python3.7/__pycache__/site.cpython-37.pyc matches /usr/lib/python3.7/site.py
#code object from '/usr/lib/python3.7/__pycache__/site.cpython-37.pyc'
#/usr/lib/python3.7/__pycache__/os.cpython-37.pyc matches /usr/lib/python3.7/os.py
#code object from '/usr/lib/python3.7/__pycache__/os.cpython-37.pyc'
#/usr/lib/python3.7/__pycache__/stat.cpython-37.pyc matches /usr/lib/python3.7/stat.py
#code object from '/usr/lib/python3.7/__pycache__/stat.cpython-37.pyc'
import '_stat'#<class '_frozen_importlib.BuiltinImporter'>
import 'stat'#<_frozen_importlib_external.SourceFileLoader object at 0x7678ae70>
#/usr/lib/python3.7/__pycache__/posixpath.cpython-37.pyc matches /usr/lib/python3.7/posixpath.py
#code object from '/usr/lib/python3.7/__pycache__/posixpath.cpython-37.pyc'
#/usr/lib/python3.7/__pycache__/genericpath.cpython-37.pyc matches /usr/lib/python3.7/genericpath.py
#code object from '/usr/lib/python3.7/__pycache__/genericpath.cpython-37.pyc'
import 'genericpath'#<_frozen_importlib_external.SourceFileLoader object at 0x76712e10>
import 'posixpath'#<_frozen_importlib_external.SourceFileLoader object at 0x7678af70>
#/usr/lib/python3.7/__pycache__/_collections_abc.cpython-37.pyc matches /usr/lib/python3.7/_collections_abc.py
#code object from '/usr/lib/python3.7/__pycache__/_collections_abc.cpython-37.pyc'
import '_collections_abc'#<_frozen_importlib_external.SourceFileLoader object at 0x76719270>
import 'os'#<_frozen_importlib_external.SourceFileLoader object at 0x76785810>
#/usr/lib/python3.7/__pycache__/_sitebuiltins.cpython-37.pyc matches /usr/lib/python3.7/_sitebuiltins.py
#code object from '/usr/lib/python3.7/__pycache__/_sitebuiltins.cpython-37.pyc'
import '_sitebuiltins'#<_frozen_importlib_external.SourceFileLoader object at 0x76785a90>
#/usr/lib/python3.7/__pycache__/sitecustomize.cpython-37.pyc matches /usr/lib/python3.7/sitecustomize.py
#code object from '/usr/lib/python3.7/__pycache__/sitecustomize.cpython-37.pyc'
import 'sitecustomize'#<_frozen_importlib_external.SourceFileLoader object at 0x7672c630>
import 'site'#<_frozen_importlib_external.SourceFileLoader object at 0x76778c90>
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
#/home/pi/test/__pycache__/vosk.cpython-37.pyc matches /home/pi/test_microphone.py
#code object from '/home/pi/test/__pycache__/vosk.cpython-37.pyc'
Traceback (most recent call last):
  File "/home/pi/test_microphone.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/test_microphone.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer
ImportError: cannot import name 'Model' from 'vosk' (/home/pi/test_microphone.py)
#clear builtins._
#clear sys.path
#clear sys.argv
#clear sys.ps1
#clear sys.ps2
#clear sys.last_type
#clear sys.last_value
#clear sys.last_traceback
#destroy vosk
#clear sys.path_hooks
#clear sys.path_importer_cache
#clear sys.meta_path
#clear sys.__interactivehook__
#clear sys.flags
#clear sys.float_info
#restore sys.stdin
#restore sys.stdout
#restore sys.stderr
#cleanup[2] removing sys
#cleanup[2] removing builtins
#cleanup[2] removing _frozen_importlib
#cleanup[2] removing _imp
#cleanup[2] removing _thread
#cleanup[2] removing _warnings
#cleanup[2] removing _weakref
#cleanup[2] removing zipimport
#cleanup[2] removing _frozen_importlib_external
#cleanup[2] removing _io
#cleanup[2] removing marshal
#cleanup[2] removing posix
#cleanup[2] removing encodings
#destroy encodings
#cleanup[2] removing codecs
#cleanup[2] removing _codecs
#cleanup[2] removing encodings.aliases
#cleanup[2] removing encodings.utf_8
#cleanup[2] removing _signal
#cleanup[2] removing __main__
#destroy __main__
#cleanup[2] removing encodings.latin_1
#cleanup[2] removing io
#destroy io
#cleanup[2] removing abc
#cleanup[2] removing _abc
#cleanup[2] removing site
#destroy site
#cleanup[2] removing os
#cleanup[2] removing stat
#cleanup[2] removing _stat
#cleanup[2] removing posixpath
#cleanup[2] removing genericpath
#cleanup[2] removing os.path
#cleanup[2] removing _collections_abc
#destroy _collections_abc
#cleanup[2] removing _sitebuiltins
#cleanup[2] removing sitecustomize
#destroy sitecustomize
#destroy zipimport
#destroy _signal
#destroy _abc
#destroy _sitebuiltins
#destroy abc
#destroy posixpath
#destroy _stat
#destroy genericpath
#destroy os
#destroy stat
#cleanup[3] wiping _frozen_importlib
#destroy _frozen_importlib_external
#cleanup[3] wiping _imp
#cleanup[3] wiping _thread
#cleanup[3] wiping _warnings
#cleanup[3] wiping _weakref
#cleanup[3] wiping _io
#cleanup[3] wiping marshal
#cleanup[3] wiping posix
#cleanup[3] wiping codecs
#cleanup[3] wiping _codecs
#cleanup[3] wiping encodings.aliases
#cleanup[3] wiping encodings.utf_8
#cleanup[3] wiping encodings.latin_1
#cleanup[3] wiping sys
#cleanup[3] wiping builtins`
```

**Comment by nshmyrev** [comment]
Format the log properly

**Comment by xMpOnEx** [comment]
Is that better?

**Comment by nshmyrev** [comment]
It looks like you have the file vosk.py in your current folder /home/pi/test and python confuses it with a system module. You'd better name vosk.py it differently.

**Comment by xMpOnEx** [comment]
Ill give it a try

**Comment by xMpOnEx** [comment]
Thats it
thanks
