### ISSUE TITLE
Python build problem: mmand '['make', 'VERBOSE=1', '_vosk']' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by gklasen** [alphacep/vosk-api#36]
I run into following issue when doing "python3 setup.py install". Kaldi indeed is cloned from lookahead-branch.

```
:~/vosk-api/python# python3 setup.py install                       running install
running bdist_egg
running egg_info
writing vosk.egg-info/PKG-INFO
writing dependency_links to vosk.egg-info/dependency_links.txt
writing top-level names to vosk.egg-info/top_level.txt
reading manifest file 'vosk.egg-info/SOURCES.txt'
writing manifest file 'vosk.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
CMake Warning at CMakeLists.txt:6 (find_package):
  By not providing "FindPython.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python" with any
  of the following names:

    PythonConfig.cmake
    python-config.cmake

  Add the installation prefix of "Python" to CMAKE_PREFIX_PATH or set
  "Python_DIR" to a directory containing one of the above files.  If "Python"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring done
-- Generating done
-- Build files have been written to: /root/vosk-api/python/build/temp.linux-x86_64-3.6
/usr/bin/cmake -H/root/vosk-api/python -B/root/vosk-api/python/build/temp.linux-x86_64-3.6 --check-build-system CMakeFiles/Makefile.cmake 0
make -f CMakeFiles/Makefile2 _vosk
make[1]: Entering directory '/root/vosk-api/python/build/temp.linux-x86_64-3.6'
/usr/bin/cmake -H/root/vosk-api/python -B/root/vosk-api/python/build/temp.linux-x86_64-3.6 --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /root/vosk-api/python/build/temp.linux-x86_64-3.6/CMakeFiles 6
make -f CMakeFiles/Makefile2 CMakeFiles/_vosk.dir/all
make[2]: Entering directory '/root/vosk-api/python/build/temp.linux-x86_64-3.6'
make -f CMakeFiles/_vosk.dir/build.make CMakeFiles/_vosk.dir/depend
make[3]: Entering directory '/root/vosk-api/python/build/temp.linux-x86_64-3.6'
cd /root/vosk-api/python/build/temp.linux-x86_64-3.6 && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /root/vosk-api/python /root/vosk-api/python /root/vosk-api/python/build/temp.linux-x86_64-3.6 /root/vosk-api/python/build/temp.linux-x86_64-3.6 /root/vosk-api/python/build/temp.linux-x86_64-3.6/CMakeFiles/_vosk.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/root/vosk-api/python/build/temp.linux-x86_64-3.6'
make -f CMakeFiles/_vosk.dir/build.make CMakeFiles/_vosk.dir/build
make[3]: Entering directory '/root/vosk-api/python/build/temp.linux-x86_64-3.6'
[ 16%] Building CXX object CMakeFiles/_vosk.dir/voskPYTHON_wrap.cxx.o
/usr/bin/c++  -D_vosk_EXPORTS -I/root/vosk-api/python/../src -I/root/kaldi/src -I/root/kaldi/tools/openfst/include  -std=c++11 -O3 -DFST_NO_DYNAMIC_LINKING  -O3 -DNDEBUG -fPIC   -o CMakeFiles/_vosk.dir/voskPYTHON_wrap.cxx.o -c /root/vosk-api/python/build/temp.linux-x86_64-3.6/voskPYTHON_wrap.cxx
/root/vosk-api/python/build/temp.linux-x86_64-3.6/voskPYTHON_wrap.cxx:173:11: fatal error: Python.h: No such file or directory
 # include <Python.h>
           ^~~~~~~~~~
compilation terminated.
CMakeFiles/_vosk.dir/build.make:71: recipe for target 'CMakeFiles/_vosk.dir/voskPYTHON_wrap.cxx.o' failed
make[3]: *** [CMakeFiles/_vosk.dir/voskPYTHON_wrap.cxx.o] Error 1
make[3]: Leaving directory '/root/vosk-api/python/build/temp.linux-x86_64-3.6'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/_vosk.dir/all' failed
make[2]: *** [CMakeFiles/_vosk.dir/all] Error 2
make[2]: Leaving directory '/root/vosk-api/python/build/temp.linux-x86_64-3.6'
CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/_vosk.dir/rule' failed
make[1]: *** [CMakeFiles/_vosk.dir/rule] Error 2
make[1]: Leaving directory '/root/vosk-api/python/build/temp.linux-x86_64-3.6'
Makefile:118: recipe for target '_vosk' failed
make: *** [_vosk] Error 2
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    python_requires='>=3.4',
  File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/usr/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_py')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/root/vosk-api/python/cmake.py", line 73, in run
    self.run_command("build_ext")
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/usr/local/lib/python3.6/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/lib/python3.6/dist-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/root/vosk-api/python/cmake.py", line 64, in build_extension
    env=env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'VERBOSE=1', '_vosk']' returned non-zero exit status 2.
```

**Comment by nshmyrev** [comment]
You need to install python development package `apt install python3-dev`.

**Comment by gklasen** [comment]
python3-dev is already the newest version (3.6.7-1~18.04).

**Comment by nshmyrev** [comment]
What is your cmake version?

**Comment by gklasen** [comment]
cmake version 3.10.2

**Comment by nshmyrev** [comment]
Can you please try to update cmake to at least 3.12.

**Comment by gklasen** [comment]
Indeed now it runs, perfect! 

CMake was the issue, updated to 3.15.2.

**Comment by nshmyrev** [comment]
Thank you, I updated cmake requirement in the sources too.
