### ISSUE TITLE
Occasional PyAudio.Stream.open() exception Errno -9998 

### ISSUE THREAD

**Issue by slowrunner** [alphacep/vosk-api#383]
I am successfully running Vosk version 0.3.16 on a Raspberry Pi 3B in two modes: command list and US English small language model for RPi.

Occasionally, the Vosk engine gets an exception at startup:
```
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
Exception:  [Errno -9998] Invalid number of channels
Traceback (most recent call last):
  File "./voicecmdr.py", line 106, in main
    vcmd = vcommand.getVoiceCommand(timeout=10)
  File "/home/pi/Carl/plib/vcommand.py", line 226, in getVoiceCommand
    stream = p.open(format=pyaudio.paInt16, channels=1, rate=16000, input=True, frames_per_buffer=8000, input_device_index = 1)
  File "/home/pi/.local/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
``` 

Usually, restarting my program after a few seconds will launch the engine successfully.

I tried catching the exception, waiting 60 seconds, and trying again (in the exception handler section), but same exception reoccurs.

Any ideas how I can catch this and succeed?

This is my invocation code:
```
				print("\nListening For A Command")
				eyes.carl_eyes(egpg,eyes.EYE_COLOR_COMMANDABLE)
				vcommand.reset_turn_start()
				try:
					vcmd = vcommand.getVoiceCommand(timeout=10)


def getVoiceCommand(model=model, rate=vosk_rate, commands=cmd_keywords, printResults=False, timeout=60):
	global dt_turn_start
	try:
		rec = KaldiRecognizer(model, vosk_rate, commands)


		p = pyaudio.PyAudio()
		# Carl needs to use input_device_index 1
		stream = p.open(format=pyaudio.paInt16, channels=1, rate=16000, input=True, frames_per_buffer=8000, input_device_index = 1)
		stream.start_stream()

		jres = None

		print("\nListening ...")
		while True:
			try:
				data = stream.read(4000,exception_on_overflow=False)
				if len(data) == 0:
					break
				if rec.AcceptWaveform(data):
					res = rec.Result()
					# print(res)
					if printResults:
						printResult(res)
					text = getText(res)
					if text != "": reset_turn_start()
					# print_w_date_time("Keyword Phrase Heard: " + text)
					break
				else:
					# print(rec.PartialResult())
					if dt_turn_start is None:
						reset_turn_start()

					elif (seconds_since_turn_start() > timeout):
						text = "TimeOut"
						break
					pass
			except KeyboardInterrupt:
				res =rec.FinalResult()
				# print("getVoiceCommand: KeyboardInterrupt - FinalResult:",res)
				text = "KeyboardInterrupt"
				break
		stream.stop_stream()
		stream.close()
	except KeyboardInterrupt:
		# print("getVoiceCommand outer try KeyboardInterrupt")
		text = "KeyboardInterrupt"

	# print("getVoiceCommand: Returning",text)
	return text
```

BTW: Here is video showing when it works (with AlphaCephei credit slide at the end):
https://player.vimeo.com/video/502786912

**Comment by nshmyrev** [comment]
We don't use pyaudio anymore, it has critical issues, try sounddevice. I see you are also using pulseaudio which is not a great idea too.

> BTW: Here is video showing when it works (with AlphaCephei credit slide at the end):
https://player.vimeo.com/video/502786912

Great, thank you!
