### ISSUE TITLE
Get a Error on Windows 10

### ISSUE THREAD

**Issue by cngun** [alphacep/vosk-api#404]
CPU：Core i5-4590 @3.30GHz 
RAM: 8 GB
Windows:Windows 10 professional 19041.746
Python:3.7.9
vosk-api:vosk-0.3.21-py3-none-win_amd64.whl

I have install vosk-api with pip3

> Processing f:\work\python\vosk-0.3.21-py3-none-win_amd64.whl
Requirement already satisfied: cffi>=1.0 in c:\users\szpeter\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from vosk==0.3.21) (1.14.4)
Requirement already satisfied: pycparser in c:\users\szpeter\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (from cffi>=1.0->vosk==0.3.21) (2.20)
Installing collected packages: vosk
Successfully installed vosk-0.3.21
WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\szpeter\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.

When I star  vosk server,it get this error

> Traceback (most recent call last):
  File ".\asr_server.py", line 11, in <module>
    from vosk import Model, KaldiRecognizer
  File "C:\Users\szpeter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\vosk\__init__.py", line 21, in <module>
    _c = open_dll()
  File "C:\Users\szpeter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\vosk\__init__.py", line 13, in open_dll
    return _ffi.dlopen("libvosk.dll")
OSError: cannot load library 'libvosk.dll': error 0x7e

How can I fix this problem?
Thanks.

**Comment by nshmyrev** [comment]
What is python output when you simply run "python.exe" ?

**Comment by cngun** [comment]
>Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 16:30:00) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by nshmyrev** [comment]
Please download dependencywalker https://www.dependencywalker.com and check if `C:\Users\szpeter\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\libvosk.dll` has any missing dependencies.

**Comment by nshmyrev** [comment]
Or this thing:

https://github.com/lucasg/Dependencies

**Comment by cngun** [comment]
>[ ? ]  API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL                           Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-APIQUERY-L1-1-1.DLL                           Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-APIQUERY-L2-1-0.DLL                           Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-APPCOMPAT-L1-1-0.DLL                          Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-APPCOMPAT-L1-1-1.DLL                          Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-APPINIT-L1-1-0.DLL                            Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-ATOMS-L1-1-0.DLL                              Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-COMM-L1-1-0.DLL                               Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-CONSOLE-L1-1-0.DLL                            Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-CONSOLE-L1-2-0.DLL                            Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-CONSOLE-L1-2-1.DLL                            Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-CONSOLE-L2-1-0.DLL                            Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-CONSOLE-L2-2-0.DLL                            Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-CONSOLE-L3-2-0.DLL                            Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-DATETIME-L1-1-0.DLL                           Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-DATETIME-L1-1-1.DLL                           Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-DATETIME-L1-1-2.DLL                           Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-DEBUG-L1-1-0.DLL                              Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-DEBUG-L1-1-1.DLL                              Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-DELAYLOAD-L1-1-0.DLL                          Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-DELAYLOAD-L1-1-1.DLL                          Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-ERRORHANDLING-L1-1-0.DLL                      Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-ERRORHANDLING-L1-1-3.DLL                      Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-FIBERS-L1-1-0.DLL                             Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-FIBERS-L2-1-0.DLL                             Error opening file. 系统找不到指定的文件。 (2).
[ ? ]  API-MS-WIN-CORE-FIBERS-L2-1-1.DLL                             Error opening file. 系统找不到指定的文件。 (2).
.............

**Comment by nshmyrev** [comment]
> [ ? ] API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL Error opening file. 系统找不到指定的文件。 (2).

Those are ok. Any issues with https://github.com/lucasg/Dependencies ?

**Comment by nshmyrev** [comment]
Do you have any other libvosk.dll somewhere in your system?

**Comment by cngun** [comment]
with https://github.com/lucasg/Dependencies
Can not find these files:
> ext-ms-win-oobe-query-l1-1-0.dll
api-ms-win-core-stringansi-l1-1-0.dll
api-ms-win-core-xstate-l2-1-0.dll
api-ms-win-core-xstate-l2-1-1.dll
api-ms-win-core-comm-l1-1-0.dll

**Comment by cngun** [comment]
In the path : c:\windows\system32\libvosk.dll

**Comment by nshmyrev** [comment]
> In the path : c:\windows\system32\libvosk.dll

You'd better remove it

**Comment by cngun** [comment]
I have deleted this file 
but still miss 2 files:

>api-ms-win-core-xstate-l2-1-1.dll
ext-ms-win-oobe-query-l1-1-0.dll

I can not search these files on google.

**Comment by nshmyrev** [comment]
> I can not search these files on google.

As I said above those are expected. 

Does the system work if you delete other libvosk.dll entries? It should be better probably. Try to remove dependencies too like libstdc++-6.dll. Probably they conflict with each other.
