### ISSUE TITLE
Java installation setups are incomplete / incorrect

### ISSUE THREAD

**Issue by suyashcjoshi** [alphacep/vosk-api#460]
I'm trying this project for the first time and was very excited to use it in my app but it's not even building the java project.

Here are the steps I tried to follow from your [website](https://alphacephei.com/vosk/install) but I ran into problems:

```
git clone https://github.com/alphacep/vosk-api
cd vosk-api/java && KALDI_ROOT=<KALDI_ROOT> make
wget https://alphacephei.com/kaldi/models/vosk-model-small-en-us-0.15.zip
unzip vosk-model-small-en-us-0.15.zip
mv vosk-model-small-en-us-0.15 model
make run
```

**Problem 1**. What is KALDI_ROOT and where does it need to be ? - `cd vosk-api/java && KALDI_ROOT=<KALDI_ROOT> make` throws error

```
gradle run

> Task :run FAILED
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'vosk':
dlopen(libvosk.dylib, 9): image not found
dlopen(libvosk.dylib, 9): image not found
dlopen(/Users/sj-lacie/Library/Frameworks/vosk.framework/vosk, 9): image not found
dlopen(/Library/Frameworks/vosk.framework/vosk, 9): image not found
dlopen(/System/Library/Frameworks/vosk.framework/vosk, 9): image not found
Native library (darwin/libvosk.dylib) not found in resource path (/Users/sj-lacie/dev/Java/Chatbot/vosk-experiment/vosk-api/java/build/classes/java/main:/Users/sj-lacie/dev/Java/Chatbot/vosk-experiment/vosk-api/java/build/resources/main:/Users/sj-lacie/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/5.7.0/a04e3db7cf0011d1b6a4bcfaee30ab20f077014b/jna-5.7.0.jar)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Native.register(Native.java:1723)
        at com.sun.jna.Native.register(Native.java:1444)
        at org.vosk.LibVosk.<clinit>(LibVosk.java:9)
        at org.vosk.DecoderTest.main(DecoderTest.java:16)
        Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libvosk.dylib, 9): image not found
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
                ... 5 more
        Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libvosk.dylib, 9): image not found
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
                ... 5 more
        Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/sj-lacie/Library/Frameworks/vosk.framework/vosk, 9): image not found
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
                ... 5 more
        Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/vosk.framework/vosk, 9): image not found
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
                ... 5 more
        Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/vosk.framework/vosk, 9): image not found
                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
                ... 5 more
        Suppressed: java.io.IOException: Native library (darwin/libvosk.dylib) not found in resource path (/Users/sj-lacie/dev/Java/Chatbot/vosk-experiment/vosk-api/java/build/classes/java/main:/Users/sj-lacie/dev/Java/Chatbot/vosk-experiment/vosk-api/java/build/resources/main:/Users/sj-lacie/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/5.7.0/a04e3db7cf0011d1b6a4bcfaee30ab20f077014b/jna-5.7.0.jar)
                at com.sun.jna.Native.extractFromResourcePath(Native.java:1096)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
                ... 5 more

FAILURE: Build failed with an exception.
```

**Problem 2**. Why are we using _make_ ? Shouldn't it be invoking _gradle_ ? I ran `gradle build` which worked and then `gradle run`, which failed and gave me this error:

**Problem 3**. Does this project structure look correct (please see attached screenshots)

**Parent Directory** : vosk-api/java

Inside of Parent Directory I have : 

- folders : src, build, and model. Inside of model folder I have the unzipped model. 
- files : build.gradle and README.md (lacking helpful instructions btw)

Thanks!

**Comment by nshmyrev** [comment]
You can find libvosk.dylib inside 

https://files.pythonhosted.org/packages/d4/d8/5e04d2c0d5f4c67e4dcd592ae3e56ac9908782044c0829561f0eeedb25d3/vosk-0.3.21-py3-none-macosx_10_6_x86_64.whl

**Comment by suyashcjoshi** [comment]
Thanks and what do I do with it? Also what do I do with Kaldi Root folder please?

**Comment by suyashcjoshi** [comment]
If you can update the installation steps that will help us all. I haven't worked with JNI before so not sure how to load that native library. Will it be in the path inside SpeakerModel.java ?

**Comment by nshmyrev** [comment]
> If you can update the installation steps that will help us all. 

Equally I'd be grateful if you update the installation steps yourself and submit a pull request.

**Comment by nshmyrev** [comment]
Instructions has been updated to use our maven repository. Demo project here:

https://github.com/alphacep/vosk-api/tree/master/java/demo
