### ISSUE TITLE
Package VOSK with Electron

### ISSUE THREAD

**Issue by Sharcoux** [alphacep/vosk-api#466]
On electron, I need to package vosk so that I can use `const vosk = require("vosk");`.

The issue I am having right now is that, when I try to execute my AppImage file, I get:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Dynamic Linking Error: /tmp/.mount_CantooClaxGf/resources/app.asar/node_modules/vosk/lib/linux-x86_64/libvosk.so: Cannot open the shared object: It's not a folder
    at new DynamicLibrary (/tmp/.mount_CantooClaxGf/resources/app.asar/node_modules/ffi-napi/lib/dynamic_library.js:75:11)
    at Object.Library (/tmp/.mount_CantooClaxGf/resources/app.asar/node_modules/ffi-napi/lib/library.js:47:10)
    at Object.<anonymous> (/tmp/.mount_CantooClaxGf/resources/app.asar/node_modules/vosk/index.js:24:21)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)

```

I tried to add vosk to the files in the build:

```
  "build": {
    "files": [
      "dist/**/*",
      "src/assets/icons/*",
      "electron.js",
      "package.json",
      "assets/models/*",
      "node_modules/vosk/lib/*"
    ],

```

I can now see the files in the `app.asar.unpacked/node_modules/vosk/lib/` folder, but when executing the app, I'm still having the same error.

How am I supposed to package the lib?

**Comment by Sharcoux** [comment]
Well, I finally succeeded,  using this config:

```json
    "extraResources": [
      "node_modules/at-least-node/**/*",
      "node_modules/builder-util-runtime/**/*",
      "node_modules/debug/**/*",
      "node_modules/ffi-napi/**/*",
      "node_modules/fs-extra/**/*",
      "node_modules/get-symbol-from-current-process-h/**/*",
      "node_modules/get-uv-event-loop-napi-h/**/*",
      "node_modules/graceful-fs/**/*",
      "node_modules/jsonfile/**/*",
      "node_modules/ms/**/*",
      "node_modules/node-addon-api/**/*",
      "node_modules/node-gyp-build/**/*",
      "node_modules/ref-napi/**/*",
      "node_modules/ref-struct-di/**/*",
      "node_modules/sax/**/*",
      "node_modules/universalify/**/*",
      "assets/models/**/*"
    ],
```

and [this lib](https://github.com/epsitec-sa/hazardous)

But this is probably not the best way to go...
Also, the Windows app is giving me this error:  
![image](https://user-images.githubusercontent.com/797545/112531154-8841ca80-8da7-11eb-9d49-f4543f516886.png)

**Comment by nshmyrev** [comment]
I believe you need to compile ffi specifically for electron.

**Comment by Sharcoux** [comment]
But isn't it what electron-builder is supposed to do with electron-rebuild ?

![image](https://user-images.githubusercontent.com/797545/112549503-38223280-8dbe-11eb-9106-ae974faeb5d4.png)

**Comment by nshmyrev** [comment]
No idea, never worked with electron. It says ffi_bindings.node is not win32 application, what is it then? Check the type/contents of that file.

**Comment by Sharcoux** [comment]
Ok, I could fix the invalid file by running: 

```
npx node-gyp -C node_modules/ffi-napi clean configure --arch=x64 --target_plataform=win32
```

I don't understand why this is needed as this should be done by `electron-rebuild`... If anyone passing by has the answer, be my guest.

Now I was still getting: 

```
0028:err:module:import_dll Library libwinpthread-1.dll (which is needed by L"D:\\win-unpacked\\resources\\app.asar.unpacked\\node_modules\\vosk\\lib\\win-x86_64\\libvosk.dll") not found
0028:err:module:import_dll Library libgcc_s_seh-1.dll (which is needed by L"D:\\win-unpacked\\resources\\app.asar.unpacked\\node_modules\\vosk\\lib\\win-x86_64\\libvosk.dll") not found
0028:err:module:import_dll Library libstdc++-6.dll (which is needed by L"D:\\win-unpacked\\resources\\app.asar.unpacked\\node_modules\\vosk\\lib\\win-x86_64\\libvosk.dll") not found
path D:\win-unpacked\resources\app.asar.unpacked\node_modules\vosk\lib\win-x86_64\libvosk.dll
```

![image](https://user-images.githubusercontent.com/797545/113211223-82e7f280-9275-11eb-8ccf-7a1783ad3ffb.png)

That I solved by copying all the dll files to the root folder: `cp node_modules/vosk/lib/win-x86_64/* .`

Now it's working.

I don't think that this is normal and I'm still trying to understand what exactly needs to be fixed. There is probably something to improve in the configuration of electron, and maybe something wrong in the ffi-napi install for Windows

**Comment by Sharcoux** [comment]
This issue will probably get it's answer from there: https://github.com/node-ffi-napi/node-ffi-napi/issues/144
