### ISSUE TITLE
Using Vosk with Node.js instead of google speech

### ISSUE THREAD

**Issue by wasweisic** [alphacep/vosk-api#497]
Hey Im using Vosk on a Node.js platform which also supports python.
Google speech was implemented using following code:

```
async function transcribe_gspeech(buffer) {
  try {
      console.log('transcribe_gspeech')
      const bytes = buffer.toString('base64');
      const audio = {
        content: bytes,
      };
      const config = {
        encoding: 'LINEAR16',
        sampleRateHertz: 48000,
        languageCode: 'de-DE',  // https://cloud.google.com/speech-to-text/docs/languages
      };
      const request = {
        audio: audio,
        config: config,
      };

      const [response] = await gspeechclient.recognize(request);
      const transcription = response.results
        .map(result => result.alternatives[0].transcript)
        .join('\n');
      console.log(`gspeech: ${transcription}`);
      return transcription;

  } catch (e) { console.log('transcribe_gspeech 368:' + e) }
}
```

I also did this on vosk_api

```
const voskClient = require('vosk');
const wav = require("wav");

vosk.setLogLevel(0);
const model = new vosk.Model("model");
const rec = new vosk.Recognizer({model: model, sampleRate: 16000.0});

const wfStream = fs.createReadStream("test.wav", {'highWaterMark': 4096});
const wfReader = new wav.Reader();

async function transcribe_vosk(buffer) {
  wfReader.on('format', async ({ audioFormat, sampleRate, channels }) => {
      if (audioFormat != 1 || channels != 1) {
          console.error("Audio file must be WAV format mono PCM.");
          process.exit(1);
      }
      for await (const data of new Readable().wrap(wfReader)) {
          const end_of_speech = rec.acceptWaveform(data);
          if (end_of_speech) {
                console.log(rec.result());
          }
      }
      console.log(rec.finalResult(rec));
      rec.free();
      model.free();
  });

  wfStream.pipe(wfReader);
}
```

But i get following error:

```
vosk.setLogLevel(0);
^

ReferenceError: vosk is not defined
    at Object.<anonymous> (/home/runner/DiscordSpeech-VOsk/index.js:1006:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1

```
Do i need to host something in background using python or did i mess up the formatting ?

**Comment by wasweisic** [comment]
Sppech input is defined as following:
```
function speak_impl(voice_Connection, mapKey) {
    voice_Connection.on('speaking', async (user, speaking) => {
        if (speaking.bitfield == 0 || user.bot) {
            return
        }
          console.log(`I'm listening to ${user.username}`)
        // this creates a 16-bit signed PCM, stereo 48KHz stream
        //VOSK PCM 16khz 16bit mono
        const audioStream = voice_Connection.receiver.createStream(user, { mode: 'pcm' })
        audioStream.on('error',  (e) => { 
            console.log('audioStream: ' + e)
        });
        let buffer = [];
        audioStream.on('data', (data) => {
            buffer.push(data)
        })
        audioStream.on('end', async () => {
            buffer = Buffer.concat(buffer)
            const duration = buffer.length / 48000 / 4;
            console.log("duration: " + duration)

            if (duration < 0.8 || duration > 19) { // 20 seconds max dur
                console.log("TOO SHORT / TOO LONG; SKPPING")
                return;
            }

            try {
                let new_buffer = await convert_audio(buffer)
                let out = await transcribe(new_buffer);
                if (out != null)
                //user.name
                    process_commands_query(out, mapKey, user.id);
            } catch (e) {
                console.log('tmpraw rename: ' + e)
            }
        })    
    })
}
```

```
async function transcribe(buffer) {

  // return transcribe_witai(buffer)
  // return transcribe_gspeech(buffer)
  return transcribe_vosk(buffer)
}
```

**Comment by nshmyrev** [comment]
```
const voskClient = require('vosk');
vosk.setLogLevel(0);
```
it should be

```
voskClient.setLogLevel(0);
```

or

```
const vosk = require('vosk');
```

> Do i need to host something in background using python or did i mess up the formatting ?

You do not need python, you need  a bit of understanding of javascript.

**Comment by solyarisoftware** [comment]
@wasweisic maybe useful: https://github.com/solyarisoftware/voskJs

**Comment by wasweisic** [comment]
ouch, lmao 😂

**Comment by solyarisoftware** [comment]
please close the issue ;-)
