### ISSUE TITLE
node.js Recognizer with SpeakerModel crash

### ISSUE THREAD

**Issue by damirn** [alphacep/vosk-api#508]
I've been trying to use Recognizer with speakerModel set from a simple node.js script:

```javascript
const fs = require('fs');
const wav = require('wav');
const { Model, Recognizer, SpeakerModel } = require('vosk');
const { Readable } = require('stream');

const model = new Model('model');
const spkModel = new SpeakerModel('model-spk');
const wfStream = fs.createReadStream('recording.wav', { highWaterMark: 4096 });
const wfReader = new wav.Reader();
const wfReadable = new Readable().wrap(wfReader);

wfReader.on('format', async ({ audioFormat, sampleRate, channels }) => {
  if (audioFormat != 1 || channels != 1) {
      console.error('Audio file must be WAV format mono PCM.');
      process.exit(1);
  }
  const rec = new Recognizer({ model, speakerModel: spkModel, sampleRate });
  for await (const data of wfReadable) {
      const endOfSpeech = await rec.acceptWaveform(data);
      if (endOfSpeech) {
          res = await JSON.parse(rec.result());
          console.log(res);
          console.log('X-vector:', JSON.stringify(res['spk']));
          console.log('Speaker distance:', cosine_dist(spk_sig, res['spk']));
      } else {
          console.log(await rec.partialResult());
      }
  }
  res = await JSON.parse(rec.finalResult());
  console.log(res);
  console.log('X-vector:', JSON.stringify(res['spk']));
})
wfStream.pipe(wfReader);
```

but this crashes with:
```
/home/node_modules/ref-napi/lib/ref.js:754
  exports._writePointer(buf, offset, ptr, true);
          ^

TypeError: error setting argument 2 - writePointer: Buffer instance expected as third argument
    at Object.writePointer (/home/node_modules/ref-napi/lib/ref.js:754:11)
    at Object.set (/home/node_modules/ref-napi/lib/ref.js:494:13)
    at Object.alloc (/home/node_modules/ref-napi/lib/ref.js:526:13)
    at Object.proxy [as vosk_recognizer_new_spk] (/home/node_modules/ffi-napi/lib/_foreign_function.js:50:28)
    at new Recognizer (/home/node_modules/vosk/index.js:224:23)
    at Reader.<anonymous> (/home/examples/vosk-audio-stream/vosk.js:17:15)
    at Reader.emit (node:events:369:20)
    at Reader._onSubchunk1 (/home/node_modules/wav/lib/reader.js:152:8)
    at process (/home/node_modules/stream-parser/index.js:270:20)
    at /home/node_modules/stream-parser/index.js:204:14
```
I'm using vosk 0.3.25 installed via npm.

**Comment by nshmyrev** [comment]
I have just pushed ee95420f8fa67a93813c014303cd0887f5758fe5 that fixes this problem

**Comment by damirn** [comment]
Thanks, it's fixed.
