### ISSUE TITLE
[JAVA] Error looking up function 'vosk_recognizer_set_max_alternatives'

### ISSUE THREAD

**Issue by epireyn** [alphacep/vosk-api#574]
Hello,

I've been getting this error every time I'm trying to parse.
```
java.lang.UnsatisfiedLinkError: Error looking up function 'vosk_recognizer_set_max_alternatives': dlsym(0x7f8aeb9481c0, vosk_recognizer_set_max_alternatives): symbol not found
	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:576)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:562)
	at com.sun.jna.Native.register(Native.java:1853)
	at com.sun.jna.Native.register(Native.java:1724)
	at org.vosk.LibVosk.<clinit>(LibVosk.java:41)
	at be.epireyn.bob.audio.stt.SpeechParser.parse(SpeechParser.java:16)
	at be.epireyn.bob.audio.AudioManager.keywordDetected(AudioManager.java:79)
	at be.epireyn.bob.audio.AudioManager.appendAudio(AudioManager.java:65)
	at be.epireyn.bob.audio.AudioReceiver.handleUserAudio(AudioReceiver.java:20)
```
I'm using the maven version 0.3.27 and vosk-model-en-us-aspire-02 (renamed in vosk-en-us-model in my resources folder)

Here is the parser code:

```Java
public static String parse(InputStream in) throws UnsupportedAudioFileException, IOException {
        LibVosk.setLogLevel(LogLevel.DEBUG);
        try (Model model = new Model("vosk-en-us-model");
             InputStream ais = AudioSystem.getAudioInputStream(in);
             Recognizer recognizer = new Recognizer(model, 16000)) {

            int nbytes;
            byte[] b = new byte[4096];
            while ((nbytes = ais.read(b)) >= 0) {
                if (recognizer.acceptWaveForm(b, nbytes)) {
                    System.out.println(recognizer.getResult());
                } else {
                    System.out.println(recognizer.getPartialResult());
                }
            }

            return recognizer.getFinalResult();
        }
    }
```

Thank you for your help

**Comment by nshmyrev** [comment]
Try 0.3.29, it should work.

**Comment by epireyn** [comment]
Thank you for your fast answer.

I've updated it but unfortunately nothing changed.

Here is the error (quite the same):
```
java.lang.UnsatisfiedLinkError: Error looking up function 'vosk_recognizer_set_max_alternatives': dlsym(0x7fa402724b90, vosk_recognizer_set_max_alternatives): symbol not found
	at com.sun.jna.Function.<init>(Function.java:252)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:600)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:576)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:562)
	at com.sun.jna.Native.register(Native.java:1853)
	at com.sun.jna.Native.register(Native.java:1724)
	at org.vosk.LibVosk.<clinit>(LibVosk.java:41)
	at be.epireyn.bob.audio.stt.SpeechParser.parse(SpeechParser.java:16)
	at be.epireyn.bob.audio.AudioManager.keywordDetected(AudioManager.java:79)
	at be.epireyn.bob.audio.AudioManager.appendAudio(AudioManager.java:65)
	at be.epireyn.bob.audio.AudioReceiver.handleUserAudio(AudioReceiver.java:20)
```

Thank you

**Comment by nshmyrev** [comment]
Hm, ok. It looks like you have an old DLL somewhere in the path and it is loaded instead of recent DLL from the jar. Try to set jna.debug_load=true property and check from where it loads libvosk.dll. Remove old version.

**Comment by epireyn** [comment]
It looks like it extracts the DLL from the jar...
Here are the logs:
```
Jun 06, 2021 2:14:15 AM com.sun.jna.Native extractFromResourcePath
INFO: Looking in classpath from jdk.internal.loader.ClassLoaders$AppClassLoader@512ddf17 for /com/sun/jna/darwin/libjnidispatch.jnilib
Jun 06, 2021 2:14:15 AM com.sun.jna.Native extractFromResourcePath
INFO: Found library resource at jar:file:/Users/epireyn/.m2/repository/net/java/dev/jna/jna/5.7.0/jna-5.7.0.jar!/com/sun/jna/darwin/libjnidispatch.jnilib
Jun 06, 2021 2:14:15 AM com.sun.jna.Native extractFromResourcePath
INFO: Extracting library to /Users/epireyn/Library/Caches/JNA/temp/jna1445828201187736483.tmp
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Looking for library 'vosk'
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Adding paths from jna.library.path: null
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Trying libvosk.dylib
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Loading failed with message: dlopen(libvosk.dylib, 9): image not found
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Adding system paths: [/usr/lib]
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Trying libvosk.dylib
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Loading failed with message: dlopen(libvosk.dylib, 9): image not found
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Trying /Users/epireyn/Library/Frameworks/vosk.framework/vosk
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Loading failed with message: dlopen(/Users/epireyn/Library/Frameworks/vosk.framework/vosk, 9): image not found
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Trying /Library/Frameworks/vosk.framework/vosk
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Loading failed with message: dlopen(/Library/Frameworks/vosk.framework/vosk, 9): image not found
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Trying /System/Library/Frameworks/vosk.framework/vosk
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Loading failed with message: dlopen(/System/Library/Frameworks/vosk.framework/vosk, 9): image not found
Jun 06, 2021 2:14:15 AM com.sun.jna.Native extractFromResourcePath
INFO: Looking in classpath from jdk.internal.loader.ClassLoaders$AppClassLoader@512ddf17 for vosk
Jun 06, 2021 2:14:15 AM com.sun.jna.Native extractFromResourcePath
INFO: Found library resource at jar:file:/Users/epireyn/.m2/repository/com/alphacephei/vosk/0.3.29/vosk-0.3.29.jar!/darwin/libvosk.dylib
Jun 06, 2021 2:14:15 AM com.sun.jna.Native extractFromResourcePath
INFO: Extracting library to /Users/epireyn/Library/Caches/JNA/temp/jna12220561218067517052.tmp
Jun 06, 2021 2:14:15 AM com.sun.jna.NativeLibrary loadLibrary
INFO: Found library 'vosk' at /Users/epireyn/Library/Caches/JNA/temp/jna12220561218067517052.tmp
```
Thank you for your support

**Comment by nshmyrev** [comment]
@epireyn ok, please clear maven cache and download 0.3.29 again and try again. I updated the dylib inside the jar.

**Comment by epireyn** [comment]
It's all good, thank you
