### ISSUE TITLE
OSError: cannot load library ... libvosk.so cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ag108** [alphacep/vosk-api#636]
Hi. I have Debian 10.10 and Python 3.7... With some troubles I installed the vosk. But have this bug:

```
/vosk-api/python/example$ ./test_simple.py test.wav 
Traceback (most recent call last):
  File "./test_simple.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer, SetLogLevel
  File "/usr/local/lib/python3.7/dist-packages/vosk-0.3.30-py3.7.egg/vosk/__init__.py", line 21, in <module>
    _c = open_dll()
  File "/usr/local/lib/python3.7/dist-packages/vosk-0.3.30-py3.7.egg/vosk/__init__.py", line 15, in open_dll
    return _ffi.dlopen(os.path.join(dlldir, "libvosk.so"))
OSError: cannot load library '/usr/local/lib/python3.7/dist-packages/vosk-0.3.30-py3.7.egg/vosk/libvosk.so': /usr/local/lib/python3.7/dist-packages/vosk-0.3.30-py3.7.egg/vosk/libvosk.so: cannot open shared object file: No such file or directory
```
 Very strange. 

Early when I try to install vosk by pip3, I have this:

```
$ sudo python3.7 -m pip install vosk
Collecting vosk
  Could not find a version that satisfies the requirement vosk (from versions: )
No matching distribution found for vosk
```

and 

```
$ sudo python3 -m pip install vosk-0.3.30-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl 
vosk-0.3.30-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl is not a supported wheel on this platform.
```

After this Vosk installed from sources...and now:

```
$ sudo pip3 install vosk
Requirement already satisfied: vosk in /usr/local/lib/python3.7/dist-packages/vosk-0.3.30-py3.7.egg (0.3.30)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.7/dist-packages (from vosk) (1.14.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.0->vosk) (2.20)

```

**Comment by nshmyrev** [comment]
You probably have arm platform or something like that. Maybe arm64.

**Comment by ag108** [comment]
> You probably have arm platform or something like that. Maybe arm64.

Thanks for reply. No I have amd64

```
# uname -a
Linux SHYAM 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
```

**Comment by ag108** [comment]
The same on another host with Debian 10.9

```
root@srv:~# pip3 install vosk
Collecting vosk
  Could not find a version that satisfies the requirement vosk (from versions: )
No matching distribution found for vosk

root@srv:~# uname -a
Linux srv 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

root@srv:~# cat /etc/debian_version 
10.9
```

**Comment by nshmyrev** [comment]
What is pip3 version?

      pip3 --version

We require pip3 at least 19.0. Do you need to update pip?

**Comment by ag108** [comment]
> What is pip3 version?
> 
> ```
>   pip3 --version
> ```
> 
> We require pip3 at least 19.0. Do you need to update pip?

Exactly! I thought for some reason that I have more than 19.0. But no. I upgraded the pip and the vosk was installed. Thanks for the help!
