### ISSUE TITLE
Using vosk with MKL

### ISSUE THREAD

**Issue by SN4KEBYTE** [alphacep/vosk-api#643]
Hello!

I want to use vosk with MKL, so I followed this steps:

- **Build Kaldi with MKL support**
```
git clone -b lookahead-1.8.0 --single-branch https://github.com/alphacep/kaldi
cd kaldi/tools
./extras/install_mkl.sh
./extras/check_dependencies.sh - gave me "OK"
make -j 4
cd ../src
./configure --shared --mkl-libdir=/opt/intel/mkl/lib/intel64_lin/ - gave me a message that Kaldi was configured for working with MKL
make clean depend -j 4
make -j 4
```

- **Build vosk with MKL support**
```
git clone https://github.com/alphacep/vosk-api
cd vosk-api/src
```

The original Makefile didn't provide build options for MKL, so I modified it like this:
```
KALDI_ROOT?=$(HOME)/travis/kaldi
MKL_ROOT?=
OPENFST_ROOT?=$(KALDI_ROOT)/tools/openfst
HAVE_CUDA?=0
CUDA_ROOT?=/usr/local/cuda
EXT?=so
CXX?=g++
HAVE_MKL=1
HAVE_ACCELERATE=0
EXTRA_CFLGAS?=
EXTRA_LDFLAGS?=

VOSK_SOURCES= \
        kaldi_recognizer.cc \
        language_model.cc \
        model.cc \
        spk_model.cc \
        vosk_api.cc

CFLAGS=-g -O2 -std=c++17 -fPIC -DFST_NO_DYNAMIC_LINKING $(EXTRA_CFLAGS) \
        -I. -I$(KALDI_ROOT)/src -I$(OPENFST_ROOT)/include

LIBS= \
        $(KALDI_ROOT)/src/online2/kaldi-online2.a \
        $(KALDI_ROOT)/src/decoder/kaldi-decoder.a \
        $(KALDI_ROOT)/src/ivector/kaldi-ivector.a \
        $(KALDI_ROOT)/src/gmm/kaldi-gmm.a \
        $(KALDI_ROOT)/src/nnet3/kaldi-nnet3.a \
        $(KALDI_ROOT)/src/tree/kaldi-tree.a \
        $(KALDI_ROOT)/src/feat/kaldi-feat.a \
        $(KALDI_ROOT)/src/lat/kaldi-lat.a \
        $(KALDI_ROOT)/src/lm/kaldi-lm.a \
        $(KALDI_ROOT)/src/rnnlm/kaldi-rnnlm.a \
        $(KALDI_ROOT)/src/hmm/kaldi-hmm.a \
        $(KALDI_ROOT)/src/transform/kaldi-transform.a \
        $(KALDI_ROOT)/src/cudamatrix/kaldi-cudamatrix.a \
        $(KALDI_ROOT)/src/matrix/kaldi-matrix.a \
        $(KALDI_ROOT)/src/fstext/kaldi-fstext.a \
        $(KALDI_ROOT)/src/util/kaldi-util.a \
        $(KALDI_ROOT)/src/base/kaldi-base.a \
        $(OPENFST_ROOT)/lib/libfst.a \
        $(OPENFST_ROOT)/lib/libfstngram.a

ifeq ($(HAVE_MKL), 1)
        CFLAGS+=-I$(MKL_ROOT)/include -L$(MKL_ROOT)/lib/intel64 -Wl,-rpath=$(MKL_ROOT)/lib/intel64 -lmkl_rt -lmkl_intel_lp64 -lmkl_core -lmkl_sequential
endif

ifeq ($(HAVE_ACCELERATE), 1)
LIBS += \
        -framework Accelerate
endif

ifeq ($(HAVE_CUDA), 1)
CFLAGS+=-DHAVE_CUDA=1 -I$(CUDA_ROOT)/include
LIBS+=-L$(CUDA_ROOT)/lib64 -lcublas -lcusparse -lcudart -lcurand -lcufft -lcusolver -lnvToolsExt
endif

all: libvosk.$(EXT)

libvosk.$(EXT): $(VOSK_SOURCES:.cc=.o)
        $(CXX) --shared -s -o $@ $^ $(LIBS) -lm -latomic $(EXTRA_LDFLAGS)

%.o: %.cc
        $(CXX) $(CFLAGS) -c -o $@ $<

clean:
        rm -f *.o *.so *.dll
```

Then I've started build process (`make -j 4`) with env variables KALDI_MKL=1, KALDI_ROOT=/path/to/my/kaldi and MKL_ROOT=/path/to/my/mkl. It didn't throw any errors.

After building vosk from source, I've installed it into my Python venv:
```
cd ../python
pip install -e .
```

- **Use LD_PRELOAD**
I've figured out that I need to use LD_PRELOAD when running Python, so I did this:
`LD_PRELOAD=/opt/intel/mkl/lib/intel64/libmkl_core.so python`

But when I'm trying to import vosk, I'm getting this strange error:
```
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vosk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tkasimov/vosk-api/python/vosk/__init__.py", line 21, in <module>
    _c = open_dll()
  File "/home/tkasimov/vosk-api/python/vosk/__init__.py", line 15, in open_dll
    return _ffi.dlopen(os.path.join(dlldir, "libvosk.so"))
OSError: cannot load library '/home/tkasimov/vosk-api/python/vosk/libvosk.so': /home/tkasimov/vosk-api/python/vosk/libvosk.so: undefined symbol: cblas_stpmv
```

What's the problem? What have I done wrong?

**Comment by nshmyrev** [comment]
>         CFLAGS+=-I$(MKL_ROOT)/include -L$(MKL_ROOT)/lib/intel64 -Wl,-rpath=$(MKL_ROOT)/lib/intel64 -lmkl_rt -lmkl_intel_lp64 -lmkl_core -lmkl_sequential

You probably have to modify LIBS with library flags, not CFLAGS.

**Comment by SN4KEBYTE** [comment]
Thanks, I'll try it!

If it'll work, is it a good idea to include this Makefile changes into vosk?

**Comment by nshmyrev** [comment]
> If it'll work, is it a good idea to include this Makefile changes into vosk?

Yes, sure

**Comment by SN4KEBYTE** [comment]
Everything works fine, thank you!

I've opened a pull request with Makefile changes: https://github.com/alphacep/vosk-api/pull/647
