### ISSUE TITLE
Dynamic Linking Error when running vosk on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by mathewthill** [alphacep/vosk-api#645]
I am trying to get vosk to run my raspberry pi zero w through nodeJS.

The binary (libvosk.so) from the python build has been copied into the node_modules/vosk/lib/linux-x86_64/ folder.

I am now getting a dynamic linking error. 

```
/home/pi/Desktop/speech/node_modules/ffi-napi/lib/dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: /home/pi/Desktop/speech/node_modules/vosk/lib/linux-x86_64/libvosk.so: undefined symbol: PyExc_ValueError
    at new DynamicLibrary (/home/pi/Desktop/speech/node_modules/ffi-napi/lib/dynamic_library.js:75:11)
    at Object.Library (/home/pi/Desktop/speech/node_modules/ffi-napi/lib/library.js:47:10)
    at Object.<anonymous> (/home/pi/Desktop/speech/node_modules/vosk/index.js:84:21)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/Desktop/speech/SpeechRecognition.js:3:12)

```
Is there any way to get armv6 binaries for vosk to run this on the RPI Zero W?

**Comment by nshmyrev** [comment]
We dropped zero support some time ago because it is too slow. Even RPi3 is on the edge.

**Comment by nshmyrev** [comment]
Similar issue for RPi4 is in #620

**Comment by nshmyrev** [comment]
Lets track this in #620
