### ISSUE TITLE
Problem with .so

### ISSUE THREAD

**Issue by gubri** [alphacep/vosk-api#663]
After succesed compiling, i have bad running(

nton@anton2:~/StoT/gjava/ex1/demo$ java demo.Demo
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'vosk':
libvosk.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
libvosk.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
Native library (linux-x86-64/libvosk.so) not found in resource path (.)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Native.register(Native.java:1746)
	at exlib.LibVosk.<clinit>(LibVosk.java:41)
	at demo.Demo.main(Demo.java:19)
	Suppressed: java.lang.UnsatisfiedLinkError: libvosk.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 4 more
	Suppressed: java.lang.UnsatisfiedLinkError: libvosk.so: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 4 more
	Suppressed: java.io.IOException: Native library (linux-x86-64/libvosk.so) not found in resource path (.)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1119)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
		... 4 more
Either i have problem with directory organisastion, or i lose library(

**Comment by nshmyrev** [comment]
It says you didn't pack libvosk.so into resources. I'm not sure how you packaged your app, so hard to give an advice.
