### ISSUE TITLE
The specified module could not be found

### ISSUE THREAD

**Issue by moeux** [alphacep/vosk-api#707]
Hi, I'm on Windows 10 and using Java.

The model I've downloaded (vosk-model-en-us-aspire-0.2) can not be found.
I've downloaded the ZIP file and extracted it into my resources folder inside IntelliJ IDEA.
I've copied the absolute path to the folder (which I renamed to model) and tried using that, but it still can't be found.

Code:
```java
try (Model model = new Model("C:\\User\\Projects\\Vosk\\src\\main\\resources\\model");
                     Recognizer recognizer = new Recognizer(model, 44100)) {
                    while (!queue.isEmpty()) {
                        byte[] data = queue.poll();

                        if (recognizer.acceptWaveForm(data, data.length))
                            System.out.println(recognizer.getResult());
                        else
                            System.out.println(recognizer.getPartialResult());
                    }
                    System.out.println(recognizer.getFinalResult());
                }
```
Exception:
```java
java.lang.UnsatisfiedLinkError: The specified module could not be found.

	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Native.register(Native.java:1723)
	at org.vosk.LibVosk.<clinit>(LibVosk.java:11)
	at org.vosk.Model.<init>(Model.java:10)
	at me.moeux.test.recognizer.SpeakCommand$SpeechRecognizer.handleUserAudio(SpeakCommand.java:55)
	at net.dv8tion.jda.internal.audio.AudioConnection.lambda$setupReceiveThread$3(AudioConnection.java:425)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by nshmyrev** [comment]
It says "module", not "model". It can not find binary module for Vosk.

Most likely because you have 32-bit java. We only support 64-bit.

**Comment by moeux** [comment]
> It says "module", not "model". It can not find binary module for Vosk.
> 
> Most likely because you have 32-bit java. We only support 64-bit.

Unlikely. This is the output of `java -version`
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

EDIT:
https://alphacephei.com/vosk/install was showing an outdated version in the `build.gradle` (0.3.21+). I've used (0.3.30+) from the `build.gradle` in the repository and now it's working. Although I'm getting empty texts.

**Comment by nshmyrev** [comment]
> Although I'm getting empty texts.

Make sure you have proper sample rate and mono audio, not stereo.

**Comment by moeux** [comment]
> Make sure you have proper sample rate and mono audio, not stereo.

This is the audio format from the `AudioInputStream`, which I've gathered programatically: `PCM_SIGNED 48000.0 Hz, 16 bit, mono, 2 bytes/frame, big-endian`
This is how I declared the model and recognizer:
```java
private final Model model = new Model(getClass().getClassLoader().getResource("model").getPath().substring(1));
        private final Recognizer recognizer = new Recognizer(model, 48000.0f);
```

Didn't see anything suspicious in the logs either, so probably still something wrong with the audio.
```
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.00600505 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:240) Loading i-vector extractor from C:/User/Projects/Vosk/build/resources/main/model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:270) Loading HCLG from C:/User/Projects/Vosk/build/resources/main/model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:285) Loading words from C:/User/Projects/Vosk/build/resources/main/model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:294) Loading winfo C:/User/Projects/Vosk/build/resources/main/model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:324) Loading CARPA model from C:/User/Projects/Vosk/build/resources/main/model/rescore/G.carpa
```

Unfortunately still empty texts, although I once got a "mm". I was saying "Hello, how are you?" though. 😄

**Comment by nshmyrev** [comment]
> This is the audio format from the AudioInputStream, which I've gathered programatically: PCM_SIGNED 48000.0 Hz, 16 bit, mono, 2 bytes/frame, big-endian

It should be little endian

**Comment by moeux** [comment]
I've been struggling on this for a few days now, still getting empty results. I'm pretty sure I've converted the audio the right way though.
I also think it's unfortunate that there is no documentation as to what the methods of `Recognizer` do.

Code:
```java
        // Stereo 48KHz 16bit stereo signed BigEndian PCM
        byte[] audioData = userAudio.getAudioData(1);
        short[] convertedAudio = new short[audioData.length / 2];
        ByteBuffer buffer = ByteBuffer.allocate(convertedAudio.length * Short.BYTES);

        // Convert to mono
        int j = 0;
        for (int i = 0; i < audioData.length; i += 2)
            convertedAudio[j++] = (short) (audioData[i] << 8 | audioData[i + 1] & 0xFF);

        // Convert to little endian
        buffer.order(ByteOrder.BIG_ENDIAN);
        for (short s : convertedAudio) buffer.putShort(s);
        buffer.order(ByteOrder.LITTLE_ENDIAN);
        buffer.rewind();

        for (int i = 0; i < convertedAudio.length; i++) convertedAudio[i] = buffer.getShort();

        queue.add(convertedAudio);
```
Output:
```
{
  "text" : ""
}
```

**Comment by nshmyrev** [comment]
```
        int j = 0;
        for (int i = 0; i < audioData.length; i += 2)
            convertedAudio[j++] = (short) (audioData[i] << 8 | audioData[i + 1] & 0xFF);
```

it doesn't look like a conversion to mono.

Most likely you messed something with conversion. You can simply save the audio after conversion before recognition to a file and listen if it is reasonable at all.

**Comment by proohit** [comment]
Hi, has this gotten solved? I am getting no results at all with a similar approach. The input format is the following: 
`48KHz 16bit stereo signed BigEndian PCM`
```java
        ...
        Model model = new Model(modelPath);
        rec = new Recognizer(model, 16000);
        ...
        byte[] voice = userAudio.getAudioData(1.0);
        AudioFormat originalFormat = new AudioFormat(48000.0f, 16, 2, true, true);
        AudioFormat targetFormat = new AudioFormat(16000.0f, 16, 1, true, false);

        int length = voice.length;
        ByteArrayInputStream bais = new ByteArrayInputStream(voice);
        AudioInputStream originalStream = new AudioInputStream(bais, originalFormat, length);
        AudioInputStream transcodedStream = AudioSystem.getAudioInputStream(targetFormat, originalStream);
        try {
            byte[] formattedVoice = transcodedStream.readAllBytes();
            if (rec.acceptWaveForm(formattedVoice, formattedVoice.length)) {
                String result = rec.getResult();
                System.out.println(result);
            }
        } catch (Exception e) {
            Logger.error(e);
        }
```
The model seems to load correctly:
```txt
LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=10 max-active=3000 lattice-beam=2
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.024034 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from path/model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:281) Loading HCL and G from path/model/graph/HCLr.fst path/model/graph/Gr.fst
LOG (VoskAPI:ReadDataFiles():model.cc:302) Loading winfo path/model/graph/phones/word_boundary.int
```
The format should be correctly represented by `javax.sound.sampled.AudioFormat`. See here:
```java
AudioFormat(float sampleRate, int sampleSizeInBits, int channels, boolean signed, boolean bigEndian)
```
The conversion itself doesn't throw anything, so I guess it is correctly transcoding.

**Comment by nshmyrev** [comment]
@proohit you'd better open a new issue. This one is solved I suppose.
