### ISSUE TITLE
Ubuntu 18.04 Java Demo Build Failure (GLIBC_2.29 not found)

### ISSUE THREAD

**Issue by alkazap** [alphacep/vosk-api#729]
Hello,

First of all, I'd like to thank you for your amazing project and constant support and kindness!

I am trying to compare the performance of Vosk API in C++/C, Python and Java (haven't found any benchmarks online). I am expecting there will be some overhead caused by Python or Java wrappers and would like to know how it affects the response time.

However, I ran into an issue when compiling Java Vosk Demo with gradle.

If I run `gradle run` inside `/vosk-api/java/demo`, I get:

```
> Task :run FAILED
Exception in thread "main" java.lang.UnsatisfiedLinkError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/alena/.cache/JNA/temp/jna17358271044219374944.tmp)
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Native.register(Native.java:1723)
        at org.vosk.LibVosk.<clinit>(LibVosk.java:41)
        at org.vosk.demo.DecoderDemo.main(DecoderDemo.java:19)

FAILURE: Build failed with an exception.
```

I am working on Ubuntu 18.04, OpenJDK 11.0.11, Gradle 7.2

The output of `strings /lib/x86_64-linux-gnu/libm.so.6 | grep GLIBC`:

```
GLIBC_2.2.5
GLIBC_2.4
GLIBC_2.15
GLIBC_2.18
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_PRIVATE
```

Could you please give me some pointers of what am I doing wrong or how to set up my environment?

**Comment by nshmyrev** [comment]
> I am expecting there will be some overhead caused by Python or Java wrappers and would like to know how it affects the response time.

There should be no difference

> The output of strings /lib/x86_64-linux-gnu/libm.so.6 | grep GLIBC:

I have just updated latest Vosk jar. Please clear gradle cache, update and try again.

**Comment by alkazap** [comment]
thank you for the fast response!

I ran:

```
rm -rf ~/.gradle/caches/
gradle clean
gradle build
gradle run
```

And still got:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/alena/.cache/JNA/temp/jna7199480673302354282.tmp)
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
        at com.sun.jna.Native.register(Native.java:1723)
        at org.vosk.LibVosk.<clinit>(LibVosk.java:41)
        at org.vosk.demo.DecoderDemo.main(DecoderDemo.java:19)
```

**Comment by nshmyrev** [comment]
Require version 0.3.32

**Comment by alkazap** [comment]
Thank you so much!

**Comment by alkazap** [comment]
forgot to confirm so posting it late
there is no difference between Python, Java and C builds
in case anyone else is curious in the future
