### ISSUE TITLE
Undefined symbol: cudaMemcpyAsync while compiling with cuda

### ISSUE THREAD

**Issue by LightTemplar** [alphacep/vosk-api#73]
If I run `python3 test_simple.py test.wav `, I get just this: `Segmentation fault`, just like this: https://github.com/alphacep/vosk-server/issues/7

Anf if I do `import vosk` under Python 3 console, I get this:

```
>>> import vosk
Traceback (most recent call last):
  File "/home/alexander/.local/lib/python3.6/site-packages/vosk-0.3.6-py3.6-linux-x86_64.egg/vosk/vosk.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/alexander/.local/lib/python3.6/site-packages/vosk-0.3.6-py3.6-linux-x86_64.egg/vosk/_vosk.so: undefined symbol: cudaMemcpyAsync

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alexander/.local/lib/python3.6/site-packages/vosk-0.3.6-py3.6-linux-x86_64.egg/vosk/__init__.py", line 1, in <module>
    from .vosk import KaldiRecognizer, Model, SpkModel
  File "/home/alexander/.local/lib/python3.6/site-packages/vosk-0.3.6-py3.6-linux-x86_64.egg/vosk/vosk.py", line 17, in <module>
    _vosk = swig_import_helper()
  File "/home/alexander/.local/lib/python3.6/site-packages/vosk-0.3.6-py3.6-linux-x86_64.egg/vosk/vosk.py", line 16, in swig_import_helper
    return importlib.import_module('_vosk')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_vosk' 
```
Similar to this: https://github.com/alphacep/vosk-server/issues/2

I have Cuda-enabled-Kaldi, but I couldn't figure out, where to include Cuda libraries and which exactly, as I'm not familiar with CMakeLists.txt, which is used for vosk-api. 
Could you please help?

**Comment by nshmyrev** [comment]
There is gpu branch in this repo, please check there how to compile with cuda:

https://github.com/alphacep/vosk-api/blob/gpu/python/CMakeLists.txt

**Comment by nshmyrev** [comment]
Btw, I have just pushed commit da39d7a58bb94e3c20536792995e86fd9543271f, now it should be in sync with master.

**Comment by LightTemplar** [comment]
You do have a gpu branch? This was a surprise for me :)
I have it cloned, and it worked perfect! Thanks a lot!
