### ISSUE TITLE
problems with calling Vosk from coroutine

### ISSUE THREAD

**Issue by rwst** [alphacep/vosk-api#901]
What could be the reason the `handler` in `StorageService.unpack()` below (from vosk-api) never delivers the message?
```
public static void unpack(Context context, String sourcePath, final String targetPath, final Callback<Model> completeCallback, final Callback<IOException> errorCallback) {
        Executor executor = Executors.newSingleThreadExecutor(); // change according to your requirements
        Handler handler = new Handler(Looper.getMainLooper());
        executor.execute(() -> {
            try {
                final String outputPath = sync(context, sourcePath, targetPath);
                Model model = new Model(outputPath);
                handler.post(() -> completeCallback.onComplete(model));        <<============
            } catch (final IOException e) {
                handler.post(() -> errorCallback.onComplete(e));
            }
        });
    }
```
The logs look fine IMHO. Do you agree?
```
V/StorageService: Making directory /storage/emulated/0/Android/data/de.lichessbyvoice/files/model/model-en-us
V/StorageService: Copy model-en-us/README to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Making directory /storage/emulated/0/Android/data/de.lichessbyvoice/files/model/model-en-us/am
V/StorageService: Copy model-en-us/am/final.mdl to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Making directory /storage/emulated/0/Android/data/de.lichessbyvoice/files/model/model-en-us/conf
V/StorageService: Copy model-en-us/conf/mfcc.conf to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Copy model-en-us/conf/model.conf to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Making directory /storage/emulated/0/Android/data/de.lichessbyvoice/files/model/model-en-us/graph
V/StorageService: Copy model-en-us/graph/Gr.fst to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Copy model-en-us/graph/HCLr.fst to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Copy model-en-us/graph/disambig_tid.int to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Making directory /storage/emulated/0/Android/data/de.lichessbyvoice/files/model/model-en-us/graph/phones
V/StorageService: Copy model-en-us/graph/phones/word_boundary.int to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Making directory /storage/emulated/0/Android/data/de.lichessbyvoice/files/model/model-en-us/ivector
V/StorageService: Copy model-en-us/ivector/final.dubm to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Copy model-en-us/ivector/final.ie to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Copy model-en-us/ivector/final.mat to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Copy model-en-us/ivector/global_cmvn.stats to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Copy model-en-us/ivector/online_cmvn.conf to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Copy model-en-us/ivector/splice.conf to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
V/StorageService: Copy model-en-us/uuid to /storage/emulated/0/Android/data/de.lichessbyvoice/files/model
I/VoskAPI: ReadDataFiles():model.cc:213) Decoding params beam=10 max-active=3000 lattice-beam=2
I/VoskAPI: ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
I/VoskAPI: RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
I/VoskAPI: RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
I/VoskAPI: CompileLooped():nnet-compile-looped.cc:345) Spent 0.0469851 seconds in looped compilation.
I/VoskAPI: ReadDataFiles():model.cc:248) Loading i-vector extractor from /storage/emulated/0/Android/data/de.lichessbyvoice/files/model/model-en-us/ivector/final.ie
I/VoskAPI: ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
I/VoskAPI: ComputeDerivedVars():ivector-extractor.cc:204) Done.
I/VoskAPI: ReadDataFiles():model.cc:281) Loading HCL and G from /storage/emulated/0/Android/data/de.lichessbyvoice/files/model/model-en-us/graph/HCLr.fst /storage/emulated/0/Android/data/de.lichessbyvoice/files/model/model-en-us/graph/Gr.fst
I/VoskAPI: ReadDataFiles():model.cc:302) Loading winfo /storage/emulated/0/Android/data/de.lichessbyvoice/files/model/model-en-us/graph/phones/word_boundary.int
```

**Comment by nshmyrev** [comment]
Hard to guess, maybe it delivers error message instead. Few extra log statements could help, you can just copy-paste this class to your code and modify

**Comment by rwst** [comment]
Thanks, great idea to just duplicate and modify. It seems that `Handler` and Kotlin coroutines may be difficult to mix. As I already am calling `unpack` from a coroutine I simplified the function to 
```
    private var model: Model? = null

    private fun unpackModel(context: Context, sourcePath: String, targetPath: String) {
        try {
            val outputPath = StorageService.sync(context, sourcePath, targetPath)
            model = Model(outputPath)
        } catch (e: IOException) {
            setErrorState(
                "Failed to unpack the model" + e.message)
        }
    }

    private fun initModel(context: Context) {
        Log.i(TAG, "unpacking model")
        unpackModel(context, "model-en-us", "model")
    }
```
simply checking `model` later for `null`. The same problem appears with `SpeechService.RecognizerThread`, see this dump:
```
  java.lang.Thread.State: RUNNABLE
	  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:583)
	  - locked <0x8656> (a android.os.MessageQueue)
	  at android.os.Handler.enqueueMessage(Handler.java:778)
	  at android.os.Handler.sendMessageAtTime(Handler.java:727)
	  at android.os.Handler.sendMessageDelayed(Handler.java:697)
	  at android.os.Handler.post(Handler.java:427)
	  at org.vosk.android.SpeechService$RecognizerThread.run(SpeechService.java:235)
```
which never calls the callbacks of `RecognitionListener` and I will replace the code using `Handler` with `Channel.send()`. Of course I could be wrong with this approach but this blogpost 
https://juliensalvi.medium.com/safe-delay-in-android-views-goodbye-handlers-hello-coroutines-cd47f53f0fbf
suggests to me that `Handler` is not the right thing anymore, if you have Kotlin coroutines.

**Comment by nshmyrev** [comment]
Nice, thank you for debugging this! Looks like we need to move in our codebase as well.
