### ISSUE TITLE
No such file .cache

### ISSUE THREAD

**Issue by jmaiden7** [alphacep/vosk-api#988]
Attempted to run: 
vosk-transcriber -i file.mp3 -o test.txt

OS: Windows SBS 2011
python version: 3.7.9
pip version: 22.1.2

Got the following error:

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\vosk-transcriber.exe\__main__.py", line 7, in <module>
  File "c:\program files\python37\lib\site-packages\vosk\transcriber\cli.py", line 62, in main
    transcriber = Transcriber(args)
  File "c:\program files\python37\lib\site-packages\vosk\transcriber\transcriber.py", line 16, in __init__
    self.model = Model(model_path=args.model, model_name=args.model_name, lang=args.lang)
  File "c:\program files\python37\lib\site-packages\vosk\__init__.py", line 50, in __init__
    model_path = self.get_model_path(model_name, lang)
  File "c:\program files\python37\lib\site-packages\vosk\__init__.py", line 63, in get_model_path
    model_path = self.get_model_by_lang(lang)
  File "c:\program files\python37\lib\site-packages\vosk\__init__.py", line 97, in get_model_by_lang
    self.download_model(Path(directory, result_model[0]))
  File "c:\program files\python37\lib\site-packages\vosk\__init__.py", line 102, in download_model
    MODEL_DIRS[3].mkdir()
  File "c:\program files\python37\lib\pathlib.py", line 1273, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\adminbusa\\.cache\\vosk'
Exception ignored in: <function Model.__del__ at 0x00000000034743A8>
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\vosk\__init__.py", line 56, in __del__
    _c.vosk_model_free(self._handle)
AttributeError: 'Model' object has no attribute '_handle'

Is this just due to the OS being older?  IE cache folder not located in the proper place?  Is there a way to set that?

**Comment by nshmyrev** [comment]
It is a bug that if .cache folder doesn't exist, it is not created automatically. Please create `C:\Users\adminbusa\.cache` and it will run fine I think.

@vadimdddd please fix asap.

**Comment by nshmyrev** [comment]
Fixed now, will be in the next release. Thank you for report.

**Comment by rloibman** [comment]
I had the same problem, created the folder ".cache" and now i get the following error:

![image](https://user-images.githubusercontent.com/91077508/178979817-d7979969-11c0-4b36-902e-456d8fa06c99.png)

Could someone help please?

**Comment by nshmyrev** [comment]
> I had the same problem, created the folder ".cache" and now i get the following error:

I see the problem is different, you'd better create new issue about it

> Could someone help please?

You need to run the script directly, not with ipython, and check the output in console.

**Comment by rloibman** [comment]
Ok, I'll do that! Thanks for helping out!
But I didn't get it, why ipython? I'm running that on Jupyter Notebook.
